# go-yaml expects the YAML field corresponding to a struct field to be lowercase. So if your struct field is
# UpdateInterval, the corresponding field in YAML is updateinterval.

nodeType: "delegate"       # should be one of "delegate", "full_node", and "lightweight"

# this doesn't matter since p2p layer is overrun by simulator
network:
    addr: "INIT BY CODE"
    msgLogsCleaningInterval: 2s
    msgLogRetention: 10s
    healthCheckInterval: 1s
    silentInterval: 5s
    peerMaintainerInterval: 1s
    allowMultiConnsperIP: true
    numPeersLowerBound: 6
    numPeersUpperBound: 12
    pingInterval: 1s
    rateLimitEnabled: false
    rateLimitPerSec: 5
    rateLimitWindowSize: 60s
    bootstrapNodes:
    maxMsgSize: 10485760
    peerDiscovery: true

chain:
    chainDBPath: "../chain.db"
    producerPrivKey: "7fbb20b87d34eade61351165aa4c6fa5d87dd349368dd6b9034ea3d3e918c706b9b8d7316705dc4ff62bb323e610f3f5072abedc9834e999d6537f6681284ea2"
    producerPubKey: "b9b8d7316705dc4ff62bb323e610f3f5072abedc9834e999d6537f6681284ea2"
    inMemTest: false

consensus:
    scheme: "ROLLDPOS"
    rollDPoS:
        proposerCB: "PseudoRotatedProposer"
        unmatchedEventTTL: 1000s
        acceptPropose:
            ttl: 1000s
        acceptPrevote:
            ttl: 1000s
        acceptVote:
            ttl: 1000s
        numSubEpochs: 1000
        eventChanSize: 1024
    blockCreationInterval: 1000s

blockSync:
    interval: 70ms

delegate:
    addrs:
        - "INIT BY CODE"

rpc:
    addr: "127.0.0.1:50051"

dispatcher:
    eventChanSize: 1024
