coverage:
  range: 50...90
  status:
    project:
      default:
        enabled: yes
        target: 75%
    patch:
      default:
        enabled: yes
        target: auto
ignore:
  - "action/protocol/rewarding/rewardingpb"
  - "action/protocol/account/accountpb"
  - "action/protocol/poll/*.abi.go"
  - "blockindex/indexpb"
  - "consensus/scheme/rolldpos/endorsementpb"
  - "db/trie/triepb"
  - "e2etest/*"
  - "ioctl/**/*"
  - "test/mock/**/*"
  - "tools/**/*"
