#I will work on this issue:)
coverage:
  range: 50...90
  status:
    project:
      default:
        enabled: yes
        target: 60%
    patch:
      default:
        enabled: yes
        target: auto