coverage:
  range: 50...90
  status:
    project:
      default:
        enabled: yes
        target: 85%
    patch:
      default:
        enabled: yes
        # allow the coverage to drop by X%
        threshold: 0%
ignore:
  - "action/protocol/rewarding/rewardingpb"
  - "action/protocol/account/accountpb"
  - "action/protocol/poll/*.abi.go"
  - "blockindex/indexpb"
  - "consensus/scheme/rolldpos/endorsementpb"
  - "db/trie/triepb"
  - "db/mock_kvstore.go"
  - "e2etest/*"
  - "ioctl/cmd/**/*"
  - "ioctl/doc/*"
  - "ioctl/flag/*"
  - "ioctl/output/*"
  - "test/mock/**/*"
  - "tools/**/*"
