coverage:
  range: 50...90
  status:
    project:
      default:
        enabled: yes
        target: 60%
    patch:
      default:
        enabled: yes
        target: auto
ignore:
  - "test/mock/**/*"
  - "consensus/scheme/rolldpos/endorsementpb"
  - "action/protocol/rewarding/rewardingpb"
  - "action/protocol/account/accountpb"
  - "db/trie/triepb"
  - "blockindex/indexpb"
  - "tools/
