# go-yaml expects the YAML field corresponding to a struct field to be lowercase. So if your struct field is
# UpdateInterval, the corresponding field in YAML is updateinterval.


nodeType: "full_node"            # should be one of "delegate", "full_node", and "lightweight"

network:
    addr: "127.0.0.1:10000"
    msgLogsCleaningInterval: 2s
    msgLogRetention: 10s
    healthCheckInterval: 1s
    silentInterval: 5s
    peerMaintainerInterval: 1s
    allowMultiConnsperIP: false
    numPeersLowerBound: 5
    numPeersUpperBound: 5
    pingInterval: 1s
    rateLimitEnabled: false
    rateLimitPerSec: 5
    rateLimitWindowSize: 60s
    bootstrapNodes: []
    tlsEnabled: false
    caCrtPath: ""
    peerCrtPath: ""
    peerKeyPath: ""
    maxMsgSize: 10485760
    peerDiscovery: true

chain:
    chainDBPath: "./chain.db"
    trieDBPath: "./trie.db"
    rawMinerAddr:
        privateKey: "925f0c9e4b6f6d92f2961d01aff6204c44d73c0b9d0da188582932d4fcad0d8ee8c66600"
        publicKey: "336eb60a5741f585a8e81de64e071327a3b96c15af4af5723598a07b6121e8e813bbd0056ba71ae29c0d64252e913f60afaeb11059908b81ff27cbfa327fd371d35f5ec0cbc01705"
        rawAddress: "io1qyqsyqcy8uhx9jtdc2xp5wx7nxyq3xf4c3jmxknzkuej8y"
    inMemTest: false

consensus:
    scheme: "NOOP"
    rollDPoS:
        proposerInterval: 3s
        unmatchedEventTTL: 3s
        acceptPropose:
            ttl: 1s
        acceptPrevote:
            ttl: 1s
        acceptVote:
            ttl: 1s
        delay: 5s
        numSubEpochs: 1
        eventChanSize: 1024
    blockCreationInterval: 1s

blockSync:
    interval: 3s

delegate:
    addrs:
        - "127.0.0.1:10000"

rpc:
    addr: "127.0.0.1::42124"

dispatcher:
    eventChanSize: 1024

explorer:
    startExplorer: false
    isTest: false
    addr: "14004"
