package ioswarm

import (
	"context"
	"fmt"
	"sync"
	"time"

	pb "github.com/iotexproject/iotex-core/v2/ioswarm/proto"
	"go.uber.org/zap"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// IOSwarmServer is the gRPC service interface.
type IOSwarmServer interface {
	Register(context.Context, *pb.RegisterRequest) (*pb.RegisterResponse, error)
	GetTasks(*pb.GetTasksRequest, IOSwarm_GetTasksServer) error
	SubmitResults(context.Context, *pb.BatchResult) (*pb.SubmitResponse, error)
	Heartbeat(context.Context, *pb.HeartbeatRequest) (*pb.HeartbeatResponse, error)
}

// IOSwarm_GetTasksServer is the server-side streaming interface for GetTasks.
type IOSwarm_GetTasksServer interface {
	Send(*pb.TaskBatch) error
	grpc.ServerStream
}

// RegisterIOSwarmServer registers the gRPC service handler.
// In production, this would be generated by protoc-gen-go-grpc.
func RegisterIOSwarmServer(s *grpc.Server, srv IOSwarmServer) {
	s.RegisterService(&_IOSwarm_serviceDesc, srv)
}

var _IOSwarm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ioswarm.IOSwarm",
	HandlerType: (*IOSwarmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _IOSwarm_Register_Handler,
		},
		{
			MethodName: "SubmitResults",
			Handler:    _IOSwarm_SubmitResults_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _IOSwarm_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTasks",
			Handler:       _IOSwarm_GetTasks_Handler,
			ServerStreams:  true,
		},
	},
	Metadata: "ioswarm.proto",
}

func _IOSwarm_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IOSwarmServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/ioswarm.IOSwarm/Register"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IOSwarmServer).Register(ctx, req.(*pb.RegisterRequest))
	})
}

func _IOSwarm_SubmitResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.BatchResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IOSwarmServer).SubmitResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/ioswarm.IOSwarm/SubmitResults"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IOSwarmServer).SubmitResults(ctx, req.(*pb.BatchResult))
	})
}

func _IOSwarm_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IOSwarmServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/ioswarm.IOSwarm/Heartbeat"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IOSwarmServer).Heartbeat(ctx, req.(*pb.HeartbeatRequest))
	})
}

func _IOSwarm_GetTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(pb.GetTasksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IOSwarmServer).GetTasks(m, &ioswarmGetTasksServer{stream})
}

type ioswarmGetTasksServer struct {
	grpc.ServerStream
}

func (x *ioswarmGetTasksServer) Send(m *pb.TaskBatch) error {
	return x.ServerStream.SendMsg(m)
}

// grpcHandler implements IOSwarmServer for the coordinator.
type grpcHandler struct {
	coord       *Coordinator
	rateLimiter sync.Map // agentID → *rateBucket
}

// rateBucket implements a simple token bucket rate limiter per agent.
type rateBucket struct {
	mu       sync.Mutex
	tokens   int
	maxBurst int
	lastTime time.Time
	rate     float64 // tokens per second
}

func newRateBucket(rate float64, burst int) *rateBucket {
	return &rateBucket{tokens: burst, maxBurst: burst, rate: rate, lastTime: time.Now()}
}

func (b *rateBucket) allow() bool {
	b.mu.Lock()
	defer b.mu.Unlock()
	now := time.Now()
	elapsed := now.Sub(b.lastTime).Seconds()
	b.lastTime = now
	b.tokens += int(elapsed * b.rate)
	if b.tokens > b.maxBurst {
		b.tokens = b.maxBurst
	}
	if b.tokens <= 0 {
		return false
	}
	b.tokens--
	return true
}

func (h *grpcHandler) getRateBucket(agentID string) *rateBucket {
	if v, ok := h.rateLimiter.Load(agentID); ok {
		return v.(*rateBucket)
	}
	b := newRateBucket(10, 20) // 10 requests/sec, burst of 20
	actual, _ := h.rateLimiter.LoadOrStore(agentID, b)
	return actual.(*rateBucket)
}

// Compile-time check that grpcHandler implements IOSwarmServer.
var _ IOSwarmServer = (*grpcHandler)(nil)

func (h *grpcHandler) Register(ctx context.Context, req *pb.RegisterRequest) (*pb.RegisterResponse, error) {
	// If HMAC auth is enabled, override the agent_id from the verified context
	if verifiedID := AgentIDFromContext(ctx); verifiedID != "" {
		req.AgentID = verifiedID
	}

	if req.AgentID == "" {
		return &pb.RegisterResponse{
			Accepted: false,
			Reason:   "agent_id is required",
		}, nil
	}

	agent, ok := h.coord.registry.Register(req)
	if !ok {
		return &pb.RegisterResponse{
			Accepted: false,
			Reason:   fmt.Sprintf("at capacity (%d agents)", h.coord.cfg.MaxAgents),
		}, nil
	}

	// Store wallet address for reward distribution
	if req.WalletAddress != "" {
		h.coord.reward.SetAgentWallet(req.AgentID, req.WalletAddress)
	}

	h.coord.logger.Info("agent registered",
		zap.String("agent", agent.ID),
		zap.String("region", agent.Region),
		zap.String("version", agent.Version),
		zap.String("wallet", req.WalletAddress))

	return &pb.RegisterResponse{
		Accepted:             true,
		HeartbeatIntervalSec: 10,
	}, nil
}

func (h *grpcHandler) GetTasks(req *pb.GetTasksRequest, stream IOSwarm_GetTasksServer) error {
	agent, ok := h.coord.registry.GetAgent(req.AgentID)
	if !ok {
		return fmt.Errorf("agent %s not registered", req.AgentID)
	}

	h.coord.logger.Info("agent started task stream",
		zap.String("agent", req.AgentID))

	// Stream task batches from the agent's channel
	for batch := range agent.TaskChan {
		if err := stream.Send(batch); err != nil {
			h.coord.logger.Warn("failed to send batch",
				zap.String("agent", req.AgentID),
				zap.Error(err))
			return err
		}
	}

	return nil
}

func (h *grpcHandler) SubmitResults(ctx context.Context, result *pb.BatchResult) (*pb.SubmitResponse, error) {
	// If HMAC auth is enabled, enforce that agent_id matches the verified identity
	if verifiedID := AgentIDFromContext(ctx); verifiedID != "" {
		if result.AgentID != verifiedID {
			return &pb.SubmitResponse{
				Accepted: false,
				Reason:   "agent_id mismatch with authenticated identity",
			}, nil
		}
	}

	// Rate limiting per agent
	if !h.getRateBucket(result.AgentID).allow() {
		return nil, status.Error(codes.ResourceExhausted, "rate limit exceeded")
	}

	// Verify agent is registered
	if _, ok := h.coord.registry.GetAgent(result.AgentID); !ok {
		return &pb.SubmitResponse{
			Accepted: false,
			Reason:   "agent not registered",
		}, nil
	}

	h.coord.handleResults(result)
	return &pb.SubmitResponse{Accepted: true}, nil
}

func (h *grpcHandler) Heartbeat(ctx context.Context, req *pb.HeartbeatRequest) (*pb.HeartbeatResponse, error) {
	alive := h.coord.registry.Heartbeat(req)
	if !alive {
		return &pb.HeartbeatResponse{
			Alive:     false,
			Directive: "shutdown",
		}, nil
	}

	// Check if there's a pending payout for this agent
	payout := h.coord.consumePayout(req.AgentID)

	return &pb.HeartbeatResponse{
		Alive:     true,
		Directive: "continue",
		Payout:    payout,
	}, nil
}
