version: '2'

services:
  iotex:
    container_name: iotex
    image: ${IOTEX_IMAGE}
    restart: on-failure
    ports:
      - 14014:14014
    volumes:
      - $IOTEX_HOME/data:/var/data:rw
      - $IOTEX_HOME/log:/var/log:rw
      - $IOTEX_HOME/etc/config.yaml:/etc/iotex/config_override.yaml:ro
      - $IOTEX_HOME/etc/genesis.yaml:/etc/iotex/genesis.yaml:ro
    command: iotex-server -config-path=/etc/iotex/config_override.yaml -genesis-path=/etc/iotex/genesis.yaml -plugin=gateway
