// Copyright (c) 2019 IoTeX
// This is an alpha (internal) release and is not suitable for production. This source code is provided 'as is' and no
// warranties are given as to title or non-infringement, merchantability or fitness for purpose and, to the extent
// permitted by law, all liability for your use of the code is disclaimed. This source code is governed by Apache
// License 2.0 that can be found in the LICENSE file.

// To compile this file:
// 1. Install the barrister translator (IDL -> JSON)
// you need to be root (or use sudo)
// pip install barrister

// 2. Install barrister-go
// go get github.com/coopernurse/barrister-go
// go install github.com/coopernurse/barrister-go/idl2go

// 3. barrister explorer.idl | $GOPATH/bin/idl2go -i -p explorer

struct CoinStatistic {
    height int
    supply string
    transfers int
    votes int
    executions int
    aps int
}

struct BlockGenerator {
    name string
    address string
}

struct Block {
    ID string
    height int
    timestamp int
    transfers int
    votes int
    executions int
    generateBy BlockGenerator
    amount string
    size int
    txRoot string
    deltaStateDigest string
}

struct Transfer {
    version int
    ID string
    nonce int
    sender string
    recipient string
    amount string
    senderPubKey string
    signature string
    payload string
    gasLimit int
    gasPrice string
    isCoinbase bool
    fee string
    timestamp int
    blockID string
    isPending bool
}

struct Execution {
    version int
    ID string
    nonce int
    executor string
    contract string
    amount string
    executorPubKey string
    signature string
    gasLimit int
    gasPrice string
    timestamp int
    data string
    blockID string
    isPending bool
}

struct Log {
    address string
    topics []string
    data string
    blockNumber int
    txnHash string
    index int
}

struct Receipt {
    returnValue string
    status int
    hash string
    gasConsumed int
    contractAddress string
    logs []Log
}

struct SendExecutionResponse {
    receipt Receipt
}

struct Vote {
    version int
    ID string
    nonce int
    timestamp int
    voter string
    votee string
    voterPubKey string
    gasLimit int
    gasPrice string
    signature string
    blockID string
    isPending bool
}

struct AddressDetails {
    address string
    totalBalance string
    nonce int
    pendingNonce int
    isCandidate bool
}

struct Candidate {
    address string
    pubKey string
    totalVote string
    isDelegate bool
    isProducer bool
}

struct CandidateMetrics {
    candidates []Candidate
    latestEpoch int
    latestHeight int
}

struct ConsensusMetrics {
    latestEpoch int
    latestDelegates []string
    latestBlockProducer string
	candidates []string
}

struct SendTransferRequest {
    version int
    nonce int
    sender string
    recipient string
    amount string
    senderPubKey string
    signature string
    payload string
    gasLimit int
    gasPrice string
    isCoinbase bool
}

struct SendTransferResponse {
    hash string
}

struct SendVoteRequest {
    version int
    nonce int
    voter string
    votee string
    voterPubKey string
    gasLimit int
    gasPrice string
    signature string
}

struct SendVoteResponse {
    hash string
}

struct PutSubChainBlockMerkelRoot {
    name string
    value string
}

struct PutSubChainBlockRequest {
    version int
    nonce int
    senderAddress string
    subChainAddress string
    height int
    roots []PutSubChainBlockMerkelRoot
    senderPubKey string
    signature string
    gasLimit int
    gasPrice string
}

struct PutSubChainBlockResponse {
    hash string
}

struct SendActionRequest {
    payload  string
}

struct SendActionResponse {
    payload  string
}

struct Node {
    address string
}

struct GetPeersResponse {
    Self Node
    Peers []Node
}

struct SendSmartContractResponse {
    hash string
}

struct GetBlkOrActResponse {
    block Block [optional]
    transfer Transfer [optional]
    vote Vote [optional]
    execution Execution [optional]
    address AddressDetails [optional]
}

struct CreateDepositRequest {
    version int
    nonce int
    chainID int
    sender string
    senderPubKey string
    recipient string
    amount string
    signature string
    gasLimit int
    gasPrice string
}

struct CreateDepositResponse {
    hash string
}

struct Deposit {
    amount string
    address string
    confirmed bool
}

struct SettleDepositRequest {
    version int
    nonce int
    sender string
    senderPubKey string
    recipient string
    amount string
    index int
    signature string
    gasLimit int
    gasPrice string
}

struct SettleDepositResponse {
    hash string
}

struct CreateDeposit {
    version int
    ID string
    nonce int
    sender string
    recipient string
    amount string
    senderPubKey string
    signature string
    gasLimit int
    gasPrice string
    fee string
    timestamp int
    blockID string
    isPending bool
}

struct SettleDeposit {
    version int
    ID string
    nonce int
    sender string
    recipient string
    amount string
    index int
    senderPubKey string
    signature string
    gasLimit int
    gasPrice string
    fee string
    timestamp int
    blockID string
    isPending bool
}

interface Explorer {
    // get the blockchain tip height
    getBlockchainHeight() int

    // get the balance of an address
    getAddressBalance(address string) string

    // get the address detail of an iotex address
    getAddressDetails(address string) AddressDetails

    // get create deposit from id
    getCreateDeposit(createDepositID string) CreateDeposit

    // get list of create deposits belonging to an address
    getCreateDepositsByAddress(address string, offset int, limit int) []CreateDeposit

    // get settle deposit from id
    getSettleDeposit(settleDepositID string) SettleDeposit

    // get list of settle deposits belonging to an address
    getSettleDepositsByAddress(address string, offset int, limit int) []SettleDeposit

    // get list of blocks by block id offset and limit
    getLastBlocksByRange(offset int, limit int) []Block

    // get block by block id
    getBlockByID(blkID string) Block

    // get statistic of iotx
    getCoinStatistic() CoinStatistic

    // get consensus metrics
    getConsensusMetrics() ConsensusMetrics

    // get candidates metrics
    getCandidateMetrics() CandidateMetrics

    // get candidates metrics at given height
    getCandidateMetricsByHeight(h int) CandidateMetrics

    // send transfer
    sendTransfer(request SendTransferRequest) SendTransferResponse

    // send vote
    sendVote(request SendVoteRequest) SendVoteResponse

    // sendSmartContract
    sendSmartContract(request Execution) SendSmartContractResponse

    // putSubChainBlock
    putSubChainBlock(request PutSubChainBlockRequest) PutSubChainBlockResponse

    // sendAction
    sendAction(request SendActionRequest) SendActionResponse

    // get list of peers
    getPeers() GetPeersResponse

    // get receipt by execution id
    getReceiptByExecutionID(id string) Receipt

    // get receipt by action id
    getReceiptByActionID(id string) Receipt

    // read execution state
    readExecutionState(request Execution) string

    // get block or action by a hash
    getBlockOrActionByHash(hashStr string) GetBlkOrActResponse

    // deposit balance from main-chain to sub-chain
    createDeposit(request CreateDepositRequest) CreateDepositResponse

    // get deposits on a sub-chain
    getDeposits(subChainID int, offset int, limit int) []Deposit

    // settle deposit on sub-chain. This is a sub-chain API
    settleDeposit(request SettleDepositRequest) SettleDepositResponse

    // suggest gas price
    suggestGasPrice() int

    // estimate gas for transfer
    estimateGasForTransfer(request SendTransferRequest) int

    // estimate gas for vote
    estimateGasForVote() int

    // estimate gas for smart contract
    estimateGasForSmartContract(request Execution) int

    // get the state root hash of a given block height
    getStateRootHash(blockHeight int) string
}
