// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package iotexapi // import "github.com/iotexproject/iotex-core/protogen/iotexapi"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import iotextypes "github.com/iotexproject/iotex-core/protogen/iotextypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetAccountRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{0}
}
func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(dst, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetAccountResponse struct {
	AccountMeta          *iotextypes.AccountMeta `protobuf:"bytes,1,opt,name=accountMeta,proto3" json:"accountMeta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{1}
}
func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountResponse.Unmarshal(m, b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
}
func (dst *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(dst, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountResponse.Size(m)
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetAccountMeta() *iotextypes.AccountMeta {
	if m != nil {
		return m.AccountMeta
	}
	return nil
}

type GetActionsRequest struct {
	// Types that are valid to be assigned to Lookup:
	//	*GetActionsRequest_ByIndex
	//	*GetActionsRequest_ByHash
	//	*GetActionsRequest_ByAddr
	//	*GetActionsRequest_UnconfirmedByAddr
	//	*GetActionsRequest_ByBlk
	Lookup               isGetActionsRequest_Lookup `protobuf_oneof:"lookup"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetActionsRequest) Reset()         { *m = GetActionsRequest{} }
func (m *GetActionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetActionsRequest) ProtoMessage()    {}
func (*GetActionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{2}
}
func (m *GetActionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActionsRequest.Unmarshal(m, b)
}
func (m *GetActionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActionsRequest.Marshal(b, m, deterministic)
}
func (dst *GetActionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActionsRequest.Merge(dst, src)
}
func (m *GetActionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetActionsRequest.Size(m)
}
func (m *GetActionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActionsRequest proto.InternalMessageInfo

type isGetActionsRequest_Lookup interface {
	isGetActionsRequest_Lookup()
}

type GetActionsRequest_ByIndex struct {
	ByIndex *GetActionsByIndexRequest `protobuf:"bytes,1,opt,name=byIndex,proto3,oneof"`
}

type GetActionsRequest_ByHash struct {
	ByHash *GetActionByHashRequest `protobuf:"bytes,2,opt,name=byHash,proto3,oneof"`
}

type GetActionsRequest_ByAddr struct {
	ByAddr *GetActionsByAddressRequest `protobuf:"bytes,3,opt,name=byAddr,proto3,oneof"`
}

type GetActionsRequest_UnconfirmedByAddr struct {
	UnconfirmedByAddr *GetUnconfirmedActionsByAddressRequest `protobuf:"bytes,4,opt,name=unconfirmedByAddr,proto3,oneof"`
}

type GetActionsRequest_ByBlk struct {
	ByBlk *GetActionsByBlockRequest `protobuf:"bytes,5,opt,name=byBlk,proto3,oneof"`
}

func (*GetActionsRequest_ByIndex) isGetActionsRequest_Lookup() {}

func (*GetActionsRequest_ByHash) isGetActionsRequest_Lookup() {}

func (*GetActionsRequest_ByAddr) isGetActionsRequest_Lookup() {}

func (*GetActionsRequest_UnconfirmedByAddr) isGetActionsRequest_Lookup() {}

func (*GetActionsRequest_ByBlk) isGetActionsRequest_Lookup() {}

func (m *GetActionsRequest) GetLookup() isGetActionsRequest_Lookup {
	if m != nil {
		return m.Lookup
	}
	return nil
}

func (m *GetActionsRequest) GetByIndex() *GetActionsByIndexRequest {
	if x, ok := m.GetLookup().(*GetActionsRequest_ByIndex); ok {
		return x.ByIndex
	}
	return nil
}

func (m *GetActionsRequest) GetByHash() *GetActionByHashRequest {
	if x, ok := m.GetLookup().(*GetActionsRequest_ByHash); ok {
		return x.ByHash
	}
	return nil
}

func (m *GetActionsRequest) GetByAddr() *GetActionsByAddressRequest {
	if x, ok := m.GetLookup().(*GetActionsRequest_ByAddr); ok {
		return x.ByAddr
	}
	return nil
}

func (m *GetActionsRequest) GetUnconfirmedByAddr() *GetUnconfirmedActionsByAddressRequest {
	if x, ok := m.GetLookup().(*GetActionsRequest_UnconfirmedByAddr); ok {
		return x.UnconfirmedByAddr
	}
	return nil
}

func (m *GetActionsRequest) GetByBlk() *GetActionsByBlockRequest {
	if x, ok := m.GetLookup().(*GetActionsRequest_ByBlk); ok {
		return x.ByBlk
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GetActionsRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GetActionsRequest_OneofMarshaler, _GetActionsRequest_OneofUnmarshaler, _GetActionsRequest_OneofSizer, []interface{}{
		(*GetActionsRequest_ByIndex)(nil),
		(*GetActionsRequest_ByHash)(nil),
		(*GetActionsRequest_ByAddr)(nil),
		(*GetActionsRequest_UnconfirmedByAddr)(nil),
		(*GetActionsRequest_ByBlk)(nil),
	}
}

func _GetActionsRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GetActionsRequest)
	// lookup
	switch x := m.Lookup.(type) {
	case *GetActionsRequest_ByIndex:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ByIndex); err != nil {
			return err
		}
	case *GetActionsRequest_ByHash:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ByHash); err != nil {
			return err
		}
	case *GetActionsRequest_ByAddr:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ByAddr); err != nil {
			return err
		}
	case *GetActionsRequest_UnconfirmedByAddr:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UnconfirmedByAddr); err != nil {
			return err
		}
	case *GetActionsRequest_ByBlk:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ByBlk); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GetActionsRequest.Lookup has unexpected type %T", x)
	}
	return nil
}

func _GetActionsRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GetActionsRequest)
	switch tag {
	case 1: // lookup.byIndex
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetActionsByIndexRequest)
		err := b.DecodeMessage(msg)
		m.Lookup = &GetActionsRequest_ByIndex{msg}
		return true, err
	case 2: // lookup.byHash
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetActionByHashRequest)
		err := b.DecodeMessage(msg)
		m.Lookup = &GetActionsRequest_ByHash{msg}
		return true, err
	case 3: // lookup.byAddr
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetActionsByAddressRequest)
		err := b.DecodeMessage(msg)
		m.Lookup = &GetActionsRequest_ByAddr{msg}
		return true, err
	case 4: // lookup.unconfirmedByAddr
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetUnconfirmedActionsByAddressRequest)
		err := b.DecodeMessage(msg)
		m.Lookup = &GetActionsRequest_UnconfirmedByAddr{msg}
		return true, err
	case 5: // lookup.byBlk
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetActionsByBlockRequest)
		err := b.DecodeMessage(msg)
		m.Lookup = &GetActionsRequest_ByBlk{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GetActionsRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GetActionsRequest)
	// lookup
	switch x := m.Lookup.(type) {
	case *GetActionsRequest_ByIndex:
		s := proto.Size(x.ByIndex)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetActionsRequest_ByHash:
		s := proto.Size(x.ByHash)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetActionsRequest_ByAddr:
		s := proto.Size(x.ByAddr)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetActionsRequest_UnconfirmedByAddr:
		s := proto.Size(x.UnconfirmedByAddr)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetActionsRequest_ByBlk:
		s := proto.Size(x.ByBlk)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GetActionsByIndexRequest struct {
	Start                uint64   `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Count                uint64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActionsByIndexRequest) Reset()         { *m = GetActionsByIndexRequest{} }
func (m *GetActionsByIndexRequest) String() string { return proto.CompactTextString(m) }
func (*GetActionsByIndexRequest) ProtoMessage()    {}
func (*GetActionsByIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{3}
}
func (m *GetActionsByIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActionsByIndexRequest.Unmarshal(m, b)
}
func (m *GetActionsByIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActionsByIndexRequest.Marshal(b, m, deterministic)
}
func (dst *GetActionsByIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActionsByIndexRequest.Merge(dst, src)
}
func (m *GetActionsByIndexRequest) XXX_Size() int {
	return xxx_messageInfo_GetActionsByIndexRequest.Size(m)
}
func (m *GetActionsByIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActionsByIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActionsByIndexRequest proto.InternalMessageInfo

func (m *GetActionsByIndexRequest) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GetActionsByIndexRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetActionByHashRequest struct {
	ActionHash           string   `protobuf:"bytes,1,opt,name=actionHash,proto3" json:"actionHash,omitempty"`
	CheckPending         bool     `protobuf:"varint,2,opt,name=checkPending,proto3" json:"checkPending,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActionByHashRequest) Reset()         { *m = GetActionByHashRequest{} }
func (m *GetActionByHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetActionByHashRequest) ProtoMessage()    {}
func (*GetActionByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{4}
}
func (m *GetActionByHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActionByHashRequest.Unmarshal(m, b)
}
func (m *GetActionByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActionByHashRequest.Marshal(b, m, deterministic)
}
func (dst *GetActionByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActionByHashRequest.Merge(dst, src)
}
func (m *GetActionByHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetActionByHashRequest.Size(m)
}
func (m *GetActionByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActionByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActionByHashRequest proto.InternalMessageInfo

func (m *GetActionByHashRequest) GetActionHash() string {
	if m != nil {
		return m.ActionHash
	}
	return ""
}

func (m *GetActionByHashRequest) GetCheckPending() bool {
	if m != nil {
		return m.CheckPending
	}
	return false
}

type GetActionsByAddressRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Start                uint64   `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Count                uint64   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActionsByAddressRequest) Reset()         { *m = GetActionsByAddressRequest{} }
func (m *GetActionsByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*GetActionsByAddressRequest) ProtoMessage()    {}
func (*GetActionsByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{5}
}
func (m *GetActionsByAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActionsByAddressRequest.Unmarshal(m, b)
}
func (m *GetActionsByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActionsByAddressRequest.Marshal(b, m, deterministic)
}
func (dst *GetActionsByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActionsByAddressRequest.Merge(dst, src)
}
func (m *GetActionsByAddressRequest) XXX_Size() int {
	return xxx_messageInfo_GetActionsByAddressRequest.Size(m)
}
func (m *GetActionsByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActionsByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActionsByAddressRequest proto.InternalMessageInfo

func (m *GetActionsByAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetActionsByAddressRequest) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GetActionsByAddressRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetUnconfirmedActionsByAddressRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Start                uint64   `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Count                uint64   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUnconfirmedActionsByAddressRequest) Reset()         { *m = GetUnconfirmedActionsByAddressRequest{} }
func (m *GetUnconfirmedActionsByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*GetUnconfirmedActionsByAddressRequest) ProtoMessage()    {}
func (*GetUnconfirmedActionsByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{6}
}
func (m *GetUnconfirmedActionsByAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUnconfirmedActionsByAddressRequest.Unmarshal(m, b)
}
func (m *GetUnconfirmedActionsByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUnconfirmedActionsByAddressRequest.Marshal(b, m, deterministic)
}
func (dst *GetUnconfirmedActionsByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUnconfirmedActionsByAddressRequest.Merge(dst, src)
}
func (m *GetUnconfirmedActionsByAddressRequest) XXX_Size() int {
	return xxx_messageInfo_GetUnconfirmedActionsByAddressRequest.Size(m)
}
func (m *GetUnconfirmedActionsByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUnconfirmedActionsByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUnconfirmedActionsByAddressRequest proto.InternalMessageInfo

func (m *GetUnconfirmedActionsByAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetUnconfirmedActionsByAddressRequest) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GetUnconfirmedActionsByAddressRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetActionsByBlockRequest struct {
	BlkHash              string   `protobuf:"bytes,1,opt,name=blkHash,proto3" json:"blkHash,omitempty"`
	Start                uint64   `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Count                uint64   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActionsByBlockRequest) Reset()         { *m = GetActionsByBlockRequest{} }
func (m *GetActionsByBlockRequest) String() string { return proto.CompactTextString(m) }
func (*GetActionsByBlockRequest) ProtoMessage()    {}
func (*GetActionsByBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{7}
}
func (m *GetActionsByBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActionsByBlockRequest.Unmarshal(m, b)
}
func (m *GetActionsByBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActionsByBlockRequest.Marshal(b, m, deterministic)
}
func (dst *GetActionsByBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActionsByBlockRequest.Merge(dst, src)
}
func (m *GetActionsByBlockRequest) XXX_Size() int {
	return xxx_messageInfo_GetActionsByBlockRequest.Size(m)
}
func (m *GetActionsByBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActionsByBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActionsByBlockRequest proto.InternalMessageInfo

func (m *GetActionsByBlockRequest) GetBlkHash() string {
	if m != nil {
		return m.BlkHash
	}
	return ""
}

func (m *GetActionsByBlockRequest) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GetActionsByBlockRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetActionsResponse struct {
	Actions              []*iotextypes.Action `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetActionsResponse) Reset()         { *m = GetActionsResponse{} }
func (m *GetActionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetActionsResponse) ProtoMessage()    {}
func (*GetActionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{8}
}
func (m *GetActionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActionsResponse.Unmarshal(m, b)
}
func (m *GetActionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActionsResponse.Marshal(b, m, deterministic)
}
func (dst *GetActionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActionsResponse.Merge(dst, src)
}
func (m *GetActionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetActionsResponse.Size(m)
}
func (m *GetActionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetActionsResponse proto.InternalMessageInfo

func (m *GetActionsResponse) GetActions() []*iotextypes.Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type GetBlockMetasRequest struct {
	// Types that are valid to be assigned to Lookup:
	//	*GetBlockMetasRequest_ByIndex
	//	*GetBlockMetasRequest_ByHash
	Lookup               isGetBlockMetasRequest_Lookup `protobuf_oneof:"lookup"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GetBlockMetasRequest) Reset()         { *m = GetBlockMetasRequest{} }
func (m *GetBlockMetasRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockMetasRequest) ProtoMessage()    {}
func (*GetBlockMetasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{9}
}
func (m *GetBlockMetasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockMetasRequest.Unmarshal(m, b)
}
func (m *GetBlockMetasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockMetasRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlockMetasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockMetasRequest.Merge(dst, src)
}
func (m *GetBlockMetasRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockMetasRequest.Size(m)
}
func (m *GetBlockMetasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockMetasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockMetasRequest proto.InternalMessageInfo

type isGetBlockMetasRequest_Lookup interface {
	isGetBlockMetasRequest_Lookup()
}

type GetBlockMetasRequest_ByIndex struct {
	ByIndex *GetBlockMetasByIndexRequest `protobuf:"bytes,1,opt,name=byIndex,proto3,oneof"`
}

type GetBlockMetasRequest_ByHash struct {
	ByHash *GetBlockMetaByHashRequest `protobuf:"bytes,2,opt,name=byHash,proto3,oneof"`
}

func (*GetBlockMetasRequest_ByIndex) isGetBlockMetasRequest_Lookup() {}

func (*GetBlockMetasRequest_ByHash) isGetBlockMetasRequest_Lookup() {}

func (m *GetBlockMetasRequest) GetLookup() isGetBlockMetasRequest_Lookup {
	if m != nil {
		return m.Lookup
	}
	return nil
}

func (m *GetBlockMetasRequest) GetByIndex() *GetBlockMetasByIndexRequest {
	if x, ok := m.GetLookup().(*GetBlockMetasRequest_ByIndex); ok {
		return x.ByIndex
	}
	return nil
}

func (m *GetBlockMetasRequest) GetByHash() *GetBlockMetaByHashRequest {
	if x, ok := m.GetLookup().(*GetBlockMetasRequest_ByHash); ok {
		return x.ByHash
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GetBlockMetasRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GetBlockMetasRequest_OneofMarshaler, _GetBlockMetasRequest_OneofUnmarshaler, _GetBlockMetasRequest_OneofSizer, []interface{}{
		(*GetBlockMetasRequest_ByIndex)(nil),
		(*GetBlockMetasRequest_ByHash)(nil),
	}
}

func _GetBlockMetasRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GetBlockMetasRequest)
	// lookup
	switch x := m.Lookup.(type) {
	case *GetBlockMetasRequest_ByIndex:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ByIndex); err != nil {
			return err
		}
	case *GetBlockMetasRequest_ByHash:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ByHash); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GetBlockMetasRequest.Lookup has unexpected type %T", x)
	}
	return nil
}

func _GetBlockMetasRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GetBlockMetasRequest)
	switch tag {
	case 1: // lookup.byIndex
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetBlockMetasByIndexRequest)
		err := b.DecodeMessage(msg)
		m.Lookup = &GetBlockMetasRequest_ByIndex{msg}
		return true, err
	case 2: // lookup.byHash
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetBlockMetaByHashRequest)
		err := b.DecodeMessage(msg)
		m.Lookup = &GetBlockMetasRequest_ByHash{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GetBlockMetasRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GetBlockMetasRequest)
	// lookup
	switch x := m.Lookup.(type) {
	case *GetBlockMetasRequest_ByIndex:
		s := proto.Size(x.ByIndex)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetBlockMetasRequest_ByHash:
		s := proto.Size(x.ByHash)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GetBlockMetasByIndexRequest struct {
	Start                uint64   `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Count                uint64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockMetasByIndexRequest) Reset()         { *m = GetBlockMetasByIndexRequest{} }
func (m *GetBlockMetasByIndexRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockMetasByIndexRequest) ProtoMessage()    {}
func (*GetBlockMetasByIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{10}
}
func (m *GetBlockMetasByIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockMetasByIndexRequest.Unmarshal(m, b)
}
func (m *GetBlockMetasByIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockMetasByIndexRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlockMetasByIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockMetasByIndexRequest.Merge(dst, src)
}
func (m *GetBlockMetasByIndexRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockMetasByIndexRequest.Size(m)
}
func (m *GetBlockMetasByIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockMetasByIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockMetasByIndexRequest proto.InternalMessageInfo

func (m *GetBlockMetasByIndexRequest) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GetBlockMetasByIndexRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetBlockMetaByHashRequest struct {
	BlkHash              string   `protobuf:"bytes,1,opt,name=blkHash,proto3" json:"blkHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockMetaByHashRequest) Reset()         { *m = GetBlockMetaByHashRequest{} }
func (m *GetBlockMetaByHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockMetaByHashRequest) ProtoMessage()    {}
func (*GetBlockMetaByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{11}
}
func (m *GetBlockMetaByHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockMetaByHashRequest.Unmarshal(m, b)
}
func (m *GetBlockMetaByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockMetaByHashRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlockMetaByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockMetaByHashRequest.Merge(dst, src)
}
func (m *GetBlockMetaByHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockMetaByHashRequest.Size(m)
}
func (m *GetBlockMetaByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockMetaByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockMetaByHashRequest proto.InternalMessageInfo

func (m *GetBlockMetaByHashRequest) GetBlkHash() string {
	if m != nil {
		return m.BlkHash
	}
	return ""
}

type GetBlockMetasResponse struct {
	BlkMetas             []*iotextypes.BlockMeta `protobuf:"bytes,1,rep,name=blkMetas,proto3" json:"blkMetas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetBlockMetasResponse) Reset()         { *m = GetBlockMetasResponse{} }
func (m *GetBlockMetasResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockMetasResponse) ProtoMessage()    {}
func (*GetBlockMetasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{12}
}
func (m *GetBlockMetasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockMetasResponse.Unmarshal(m, b)
}
func (m *GetBlockMetasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockMetasResponse.Marshal(b, m, deterministic)
}
func (dst *GetBlockMetasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockMetasResponse.Merge(dst, src)
}
func (m *GetBlockMetasResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockMetasResponse.Size(m)
}
func (m *GetBlockMetasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockMetasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockMetasResponse proto.InternalMessageInfo

func (m *GetBlockMetasResponse) GetBlkMetas() []*iotextypes.BlockMeta {
	if m != nil {
		return m.BlkMetas
	}
	return nil
}

type GetChainMetaRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChainMetaRequest) Reset()         { *m = GetChainMetaRequest{} }
func (m *GetChainMetaRequest) String() string { return proto.CompactTextString(m) }
func (*GetChainMetaRequest) ProtoMessage()    {}
func (*GetChainMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{13}
}
func (m *GetChainMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChainMetaRequest.Unmarshal(m, b)
}
func (m *GetChainMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChainMetaRequest.Marshal(b, m, deterministic)
}
func (dst *GetChainMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChainMetaRequest.Merge(dst, src)
}
func (m *GetChainMetaRequest) XXX_Size() int {
	return xxx_messageInfo_GetChainMetaRequest.Size(m)
}
func (m *GetChainMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChainMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChainMetaRequest proto.InternalMessageInfo

type GetChainMetaResponse struct {
	ChainMeta            *iotextypes.ChainMeta `protobuf:"bytes,1,opt,name=chainMeta,proto3" json:"chainMeta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetChainMetaResponse) Reset()         { *m = GetChainMetaResponse{} }
func (m *GetChainMetaResponse) String() string { return proto.CompactTextString(m) }
func (*GetChainMetaResponse) ProtoMessage()    {}
func (*GetChainMetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{14}
}
func (m *GetChainMetaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChainMetaResponse.Unmarshal(m, b)
}
func (m *GetChainMetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChainMetaResponse.Marshal(b, m, deterministic)
}
func (dst *GetChainMetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChainMetaResponse.Merge(dst, src)
}
func (m *GetChainMetaResponse) XXX_Size() int {
	return xxx_messageInfo_GetChainMetaResponse.Size(m)
}
func (m *GetChainMetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChainMetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetChainMetaResponse proto.InternalMessageInfo

func (m *GetChainMetaResponse) GetChainMeta() *iotextypes.ChainMeta {
	if m != nil {
		return m.ChainMeta
	}
	return nil
}

type SendActionRequest struct {
	Action               *iotextypes.Action `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SendActionRequest) Reset()         { *m = SendActionRequest{} }
func (m *SendActionRequest) String() string { return proto.CompactTextString(m) }
func (*SendActionRequest) ProtoMessage()    {}
func (*SendActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{15}
}
func (m *SendActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendActionRequest.Unmarshal(m, b)
}
func (m *SendActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendActionRequest.Marshal(b, m, deterministic)
}
func (dst *SendActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendActionRequest.Merge(dst, src)
}
func (m *SendActionRequest) XXX_Size() int {
	return xxx_messageInfo_SendActionRequest.Size(m)
}
func (m *SendActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendActionRequest proto.InternalMessageInfo

func (m *SendActionRequest) GetAction() *iotextypes.Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type SendActionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendActionResponse) Reset()         { *m = SendActionResponse{} }
func (m *SendActionResponse) String() string { return proto.CompactTextString(m) }
func (*SendActionResponse) ProtoMessage()    {}
func (*SendActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{16}
}
func (m *SendActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendActionResponse.Unmarshal(m, b)
}
func (m *SendActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendActionResponse.Marshal(b, m, deterministic)
}
func (dst *SendActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendActionResponse.Merge(dst, src)
}
func (m *SendActionResponse) XXX_Size() int {
	return xxx_messageInfo_SendActionResponse.Size(m)
}
func (m *SendActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendActionResponse proto.InternalMessageInfo

type GetReceiptByActionRequest struct {
	ActionHash           string   `protobuf:"bytes,1,opt,name=actionHash,proto3" json:"actionHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReceiptByActionRequest) Reset()         { *m = GetReceiptByActionRequest{} }
func (m *GetReceiptByActionRequest) String() string { return proto.CompactTextString(m) }
func (*GetReceiptByActionRequest) ProtoMessage()    {}
func (*GetReceiptByActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{17}
}
func (m *GetReceiptByActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReceiptByActionRequest.Unmarshal(m, b)
}
func (m *GetReceiptByActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReceiptByActionRequest.Marshal(b, m, deterministic)
}
func (dst *GetReceiptByActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReceiptByActionRequest.Merge(dst, src)
}
func (m *GetReceiptByActionRequest) XXX_Size() int {
	return xxx_messageInfo_GetReceiptByActionRequest.Size(m)
}
func (m *GetReceiptByActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReceiptByActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReceiptByActionRequest proto.InternalMessageInfo

func (m *GetReceiptByActionRequest) GetActionHash() string {
	if m != nil {
		return m.ActionHash
	}
	return ""
}

type GetReceiptByActionResponse struct {
	Receipt              *iotextypes.Receipt `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetReceiptByActionResponse) Reset()         { *m = GetReceiptByActionResponse{} }
func (m *GetReceiptByActionResponse) String() string { return proto.CompactTextString(m) }
func (*GetReceiptByActionResponse) ProtoMessage()    {}
func (*GetReceiptByActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{18}
}
func (m *GetReceiptByActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReceiptByActionResponse.Unmarshal(m, b)
}
func (m *GetReceiptByActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReceiptByActionResponse.Marshal(b, m, deterministic)
}
func (dst *GetReceiptByActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReceiptByActionResponse.Merge(dst, src)
}
func (m *GetReceiptByActionResponse) XXX_Size() int {
	return xxx_messageInfo_GetReceiptByActionResponse.Size(m)
}
func (m *GetReceiptByActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReceiptByActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReceiptByActionResponse proto.InternalMessageInfo

func (m *GetReceiptByActionResponse) GetReceipt() *iotextypes.Receipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

type ReadContractRequest struct {
	Action               *iotextypes.Action `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReadContractRequest) Reset()         { *m = ReadContractRequest{} }
func (m *ReadContractRequest) String() string { return proto.CompactTextString(m) }
func (*ReadContractRequest) ProtoMessage()    {}
func (*ReadContractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{19}
}
func (m *ReadContractRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadContractRequest.Unmarshal(m, b)
}
func (m *ReadContractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadContractRequest.Marshal(b, m, deterministic)
}
func (dst *ReadContractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadContractRequest.Merge(dst, src)
}
func (m *ReadContractRequest) XXX_Size() int {
	return xxx_messageInfo_ReadContractRequest.Size(m)
}
func (m *ReadContractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadContractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadContractRequest proto.InternalMessageInfo

func (m *ReadContractRequest) GetAction() *iotextypes.Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type ReadContractResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadContractResponse) Reset()         { *m = ReadContractResponse{} }
func (m *ReadContractResponse) String() string { return proto.CompactTextString(m) }
func (*ReadContractResponse) ProtoMessage()    {}
func (*ReadContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{20}
}
func (m *ReadContractResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadContractResponse.Unmarshal(m, b)
}
func (m *ReadContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadContractResponse.Marshal(b, m, deterministic)
}
func (dst *ReadContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadContractResponse.Merge(dst, src)
}
func (m *ReadContractResponse) XXX_Size() int {
	return xxx_messageInfo_ReadContractResponse.Size(m)
}
func (m *ReadContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadContractResponse proto.InternalMessageInfo

func (m *ReadContractResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SuggestGasPriceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuggestGasPriceRequest) Reset()         { *m = SuggestGasPriceRequest{} }
func (m *SuggestGasPriceRequest) String() string { return proto.CompactTextString(m) }
func (*SuggestGasPriceRequest) ProtoMessage()    {}
func (*SuggestGasPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{21}
}
func (m *SuggestGasPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuggestGasPriceRequest.Unmarshal(m, b)
}
func (m *SuggestGasPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuggestGasPriceRequest.Marshal(b, m, deterministic)
}
func (dst *SuggestGasPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuggestGasPriceRequest.Merge(dst, src)
}
func (m *SuggestGasPriceRequest) XXX_Size() int {
	return xxx_messageInfo_SuggestGasPriceRequest.Size(m)
}
func (m *SuggestGasPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SuggestGasPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SuggestGasPriceRequest proto.InternalMessageInfo

type SuggestGasPriceResponse struct {
	GasPrice             uint64   `protobuf:"varint,1,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuggestGasPriceResponse) Reset()         { *m = SuggestGasPriceResponse{} }
func (m *SuggestGasPriceResponse) String() string { return proto.CompactTextString(m) }
func (*SuggestGasPriceResponse) ProtoMessage()    {}
func (*SuggestGasPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{22}
}
func (m *SuggestGasPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuggestGasPriceResponse.Unmarshal(m, b)
}
func (m *SuggestGasPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuggestGasPriceResponse.Marshal(b, m, deterministic)
}
func (dst *SuggestGasPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuggestGasPriceResponse.Merge(dst, src)
}
func (m *SuggestGasPriceResponse) XXX_Size() int {
	return xxx_messageInfo_SuggestGasPriceResponse.Size(m)
}
func (m *SuggestGasPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SuggestGasPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SuggestGasPriceResponse proto.InternalMessageInfo

func (m *SuggestGasPriceResponse) GetGasPrice() uint64 {
	if m != nil {
		return m.GasPrice
	}
	return 0
}

type EstimateGasForActionRequest struct {
	Action               *iotextypes.Action `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EstimateGasForActionRequest) Reset()         { *m = EstimateGasForActionRequest{} }
func (m *EstimateGasForActionRequest) String() string { return proto.CompactTextString(m) }
func (*EstimateGasForActionRequest) ProtoMessage()    {}
func (*EstimateGasForActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{23}
}
func (m *EstimateGasForActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstimateGasForActionRequest.Unmarshal(m, b)
}
func (m *EstimateGasForActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstimateGasForActionRequest.Marshal(b, m, deterministic)
}
func (dst *EstimateGasForActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstimateGasForActionRequest.Merge(dst, src)
}
func (m *EstimateGasForActionRequest) XXX_Size() int {
	return xxx_messageInfo_EstimateGasForActionRequest.Size(m)
}
func (m *EstimateGasForActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EstimateGasForActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EstimateGasForActionRequest proto.InternalMessageInfo

func (m *EstimateGasForActionRequest) GetAction() *iotextypes.Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type EstimateGasForActionResponse struct {
	Gas                  uint64   `protobuf:"varint,1,opt,name=gas,proto3" json:"gas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstimateGasForActionResponse) Reset()         { *m = EstimateGasForActionResponse{} }
func (m *EstimateGasForActionResponse) String() string { return proto.CompactTextString(m) }
func (*EstimateGasForActionResponse) ProtoMessage()    {}
func (*EstimateGasForActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_7407a1b92915c4a6, []int{24}
}
func (m *EstimateGasForActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstimateGasForActionResponse.Unmarshal(m, b)
}
func (m *EstimateGasForActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstimateGasForActionResponse.Marshal(b, m, deterministic)
}
func (dst *EstimateGasForActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstimateGasForActionResponse.Merge(dst, src)
}
func (m *EstimateGasForActionResponse) XXX_Size() int {
	return xxx_messageInfo_EstimateGasForActionResponse.Size(m)
}
func (m *EstimateGasForActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EstimateGasForActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EstimateGasForActionResponse proto.InternalMessageInfo

func (m *EstimateGasForActionResponse) GetGas() uint64 {
	if m != nil {
		return m.Gas
	}
	return 0
}

func init() {
	proto.RegisterType((*GetAccountRequest)(nil), "iotexapi.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "iotexapi.GetAccountResponse")
	proto.RegisterType((*GetActionsRequest)(nil), "iotexapi.GetActionsRequest")
	proto.RegisterType((*GetActionsByIndexRequest)(nil), "iotexapi.GetActionsByIndexRequest")
	proto.RegisterType((*GetActionByHashRequest)(nil), "iotexapi.GetActionByHashRequest")
	proto.RegisterType((*GetActionsByAddressRequest)(nil), "iotexapi.GetActionsByAddressRequest")
	proto.RegisterType((*GetUnconfirmedActionsByAddressRequest)(nil), "iotexapi.GetUnconfirmedActionsByAddressRequest")
	proto.RegisterType((*GetActionsByBlockRequest)(nil), "iotexapi.GetActionsByBlockRequest")
	proto.RegisterType((*GetActionsResponse)(nil), "iotexapi.GetActionsResponse")
	proto.RegisterType((*GetBlockMetasRequest)(nil), "iotexapi.GetBlockMetasRequest")
	proto.RegisterType((*GetBlockMetasByIndexRequest)(nil), "iotexapi.GetBlockMetasByIndexRequest")
	proto.RegisterType((*GetBlockMetaByHashRequest)(nil), "iotexapi.GetBlockMetaByHashRequest")
	proto.RegisterType((*GetBlockMetasResponse)(nil), "iotexapi.GetBlockMetasResponse")
	proto.RegisterType((*GetChainMetaRequest)(nil), "iotexapi.GetChainMetaRequest")
	proto.RegisterType((*GetChainMetaResponse)(nil), "iotexapi.GetChainMetaResponse")
	proto.RegisterType((*SendActionRequest)(nil), "iotexapi.SendActionRequest")
	proto.RegisterType((*SendActionResponse)(nil), "iotexapi.SendActionResponse")
	proto.RegisterType((*GetReceiptByActionRequest)(nil), "iotexapi.GetReceiptByActionRequest")
	proto.RegisterType((*GetReceiptByActionResponse)(nil), "iotexapi.GetReceiptByActionResponse")
	proto.RegisterType((*ReadContractRequest)(nil), "iotexapi.ReadContractRequest")
	proto.RegisterType((*ReadContractResponse)(nil), "iotexapi.ReadContractResponse")
	proto.RegisterType((*SuggestGasPriceRequest)(nil), "iotexapi.SuggestGasPriceRequest")
	proto.RegisterType((*SuggestGasPriceResponse)(nil), "iotexapi.SuggestGasPriceResponse")
	proto.RegisterType((*EstimateGasForActionRequest)(nil), "iotexapi.EstimateGasForActionRequest")
	proto.RegisterType((*EstimateGasForActionResponse)(nil), "iotexapi.EstimateGasForActionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIServiceClient is the client API for APIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIServiceClient interface {
	// get the address detail of an address
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
	// get action(s) by:
	// 1. start index and action count
	// 2. action hash
	// 3. address with start index and action count
	// 4. get unconfirmed actions by address with start index and action count
	// 5. block hash with start index and action count
	GetActions(ctx context.Context, in *GetActionsRequest, opts ...grpc.CallOption) (*GetActionsResponse, error)
	// get block metadata(s) by:
	// 1. start index and block count
	// 2. block hash
	GetBlockMetas(ctx context.Context, in *GetBlockMetasRequest, opts ...grpc.CallOption) (*GetBlockMetasResponse, error)
	// get chain metadata
	GetChainMeta(ctx context.Context, in *GetChainMetaRequest, opts ...grpc.CallOption) (*GetChainMetaResponse, error)
	// sendAction
	SendAction(ctx context.Context, in *SendActionRequest, opts ...grpc.CallOption) (*SendActionResponse, error)
	// get receipt by action Hash
	GetReceiptByAction(ctx context.Context, in *GetReceiptByActionRequest, opts ...grpc.CallOption) (*GetReceiptByActionResponse, error)
	// TODO: read contract
	ReadContract(ctx context.Context, in *ReadContractRequest, opts ...grpc.CallOption) (*ReadContractResponse, error)
	// suggest gas price
	SuggestGasPrice(ctx context.Context, in *SuggestGasPriceRequest, opts ...grpc.CallOption) (*SuggestGasPriceResponse, error)
	// estimate gas for action
	EstimateGasForAction(ctx context.Context, in *EstimateGasForActionRequest, opts ...grpc.CallOption) (*EstimateGasForActionResponse, error)
}

type aPIServiceClient struct {
	cc *grpc.ClientConn
}

func NewAPIServiceClient(cc *grpc.ClientConn) APIServiceClient {
	return &aPIServiceClient{cc}
}

func (c *aPIServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, "/iotexapi.APIService/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetActions(ctx context.Context, in *GetActionsRequest, opts ...grpc.CallOption) (*GetActionsResponse, error) {
	out := new(GetActionsResponse)
	err := c.cc.Invoke(ctx, "/iotexapi.APIService/GetActions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetBlockMetas(ctx context.Context, in *GetBlockMetasRequest, opts ...grpc.CallOption) (*GetBlockMetasResponse, error) {
	out := new(GetBlockMetasResponse)
	err := c.cc.Invoke(ctx, "/iotexapi.APIService/GetBlockMetas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetChainMeta(ctx context.Context, in *GetChainMetaRequest, opts ...grpc.CallOption) (*GetChainMetaResponse, error) {
	out := new(GetChainMetaResponse)
	err := c.cc.Invoke(ctx, "/iotexapi.APIService/GetChainMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) SendAction(ctx context.Context, in *SendActionRequest, opts ...grpc.CallOption) (*SendActionResponse, error) {
	out := new(SendActionResponse)
	err := c.cc.Invoke(ctx, "/iotexapi.APIService/SendAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetReceiptByAction(ctx context.Context, in *GetReceiptByActionRequest, opts ...grpc.CallOption) (*GetReceiptByActionResponse, error) {
	out := new(GetReceiptByActionResponse)
	err := c.cc.Invoke(ctx, "/iotexapi.APIService/GetReceiptByAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) ReadContract(ctx context.Context, in *ReadContractRequest, opts ...grpc.CallOption) (*ReadContractResponse, error) {
	out := new(ReadContractResponse)
	err := c.cc.Invoke(ctx, "/iotexapi.APIService/ReadContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) SuggestGasPrice(ctx context.Context, in *SuggestGasPriceRequest, opts ...grpc.CallOption) (*SuggestGasPriceResponse, error) {
	out := new(SuggestGasPriceResponse)
	err := c.cc.Invoke(ctx, "/iotexapi.APIService/SuggestGasPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) EstimateGasForAction(ctx context.Context, in *EstimateGasForActionRequest, opts ...grpc.CallOption) (*EstimateGasForActionResponse, error) {
	out := new(EstimateGasForActionResponse)
	err := c.cc.Invoke(ctx, "/iotexapi.APIService/EstimateGasForAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServiceServer is the server API for APIService service.
type APIServiceServer interface {
	// get the address detail of an address
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	// get action(s) by:
	// 1. start index and action count
	// 2. action hash
	// 3. address with start index and action count
	// 4. get unconfirmed actions by address with start index and action count
	// 5. block hash with start index and action count
	GetActions(context.Context, *GetActionsRequest) (*GetActionsResponse, error)
	// get block metadata(s) by:
	// 1. start index and block count
	// 2. block hash
	GetBlockMetas(context.Context, *GetBlockMetasRequest) (*GetBlockMetasResponse, error)
	// get chain metadata
	GetChainMeta(context.Context, *GetChainMetaRequest) (*GetChainMetaResponse, error)
	// sendAction
	SendAction(context.Context, *SendActionRequest) (*SendActionResponse, error)
	// get receipt by action Hash
	GetReceiptByAction(context.Context, *GetReceiptByActionRequest) (*GetReceiptByActionResponse, error)
	// TODO: read contract
	ReadContract(context.Context, *ReadContractRequest) (*ReadContractResponse, error)
	// suggest gas price
	SuggestGasPrice(context.Context, *SuggestGasPriceRequest) (*SuggestGasPriceResponse, error)
	// estimate gas for action
	EstimateGasForAction(context.Context, *EstimateGasForActionRequest) (*EstimateGasForActionResponse, error)
}

func RegisterAPIServiceServer(s *grpc.Server, srv APIServiceServer) {
	s.RegisterService(&_APIService_serviceDesc, srv)
}

func _APIService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotexapi.APIService/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotexapi.APIService/GetActions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetActions(ctx, req.(*GetActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetBlockMetas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockMetasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetBlockMetas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotexapi.APIService/GetBlockMetas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetBlockMetas(ctx, req.(*GetBlockMetasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetChainMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChainMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetChainMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotexapi.APIService/GetChainMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetChainMeta(ctx, req.(*GetChainMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_SendAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).SendAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotexapi.APIService/SendAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).SendAction(ctx, req.(*SendActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetReceiptByAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReceiptByActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetReceiptByAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotexapi.APIService/GetReceiptByAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetReceiptByAction(ctx, req.(*GetReceiptByActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_ReadContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).ReadContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotexapi.APIService/ReadContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).ReadContract(ctx, req.(*ReadContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_SuggestGasPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestGasPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).SuggestGasPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotexapi.APIService/SuggestGasPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).SuggestGasPrice(ctx, req.(*SuggestGasPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_EstimateGasForAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateGasForActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).EstimateGasForAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iotexapi.APIService/EstimateGasForAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).EstimateGasForAction(ctx, req.(*EstimateGasForActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _APIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iotexapi.APIService",
	HandlerType: (*APIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _APIService_GetAccount_Handler,
		},
		{
			MethodName: "GetActions",
			Handler:    _APIService_GetActions_Handler,
		},
		{
			MethodName: "GetBlockMetas",
			Handler:    _APIService_GetBlockMetas_Handler,
		},
		{
			MethodName: "GetChainMeta",
			Handler:    _APIService_GetChainMeta_Handler,
		},
		{
			MethodName: "SendAction",
			Handler:    _APIService_SendAction_Handler,
		},
		{
			MethodName: "GetReceiptByAction",
			Handler:    _APIService_GetReceiptByAction_Handler,
		},
		{
			MethodName: "ReadContract",
			Handler:    _APIService_ReadContract_Handler,
		},
		{
			MethodName: "SuggestGasPrice",
			Handler:    _APIService_SuggestGasPrice_Handler,
		},
		{
			MethodName: "EstimateGasForAction",
			Handler:    _APIService_EstimateGasForAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_7407a1b92915c4a6) }

var fileDescriptor_api_7407a1b92915c4a6 = []byte{
	// 899 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x7f, 0x6f, 0xdb, 0x44,
	0x18, 0x4e, 0x9b, 0x34, 0x3f, 0xde, 0x16, 0xb1, 0x5e, 0xd3, 0xcd, 0x78, 0xa3, 0x8c, 0x63, 0x43,
	0xd3, 0x44, 0x13, 0xe8, 0x18, 0x12, 0x43, 0x0c, 0xc5, 0x15, 0x4d, 0x43, 0x85, 0x5a, 0xb9, 0x42,
	0x42, 0x08, 0x09, 0xce, 0xe7, 0xc3, 0x31, 0x49, 0x6c, 0x63, 0x5f, 0x50, 0xf3, 0x11, 0xf8, 0x1a,
	0x7c, 0x48, 0xfe, 0x46, 0xbe, 0x3b, 0xc7, 0xe7, 0xc4, 0x4e, 0x69, 0xc5, 0x7f, 0xb9, 0xf7, 0xde,
	0xe7, 0x79, 0x7f, 0x3e, 0xe7, 0x40, 0x87, 0x44, 0x7e, 0x2f, 0x8a, 0x43, 0x1e, 0xa2, 0xb6, 0x1f,
	0x72, 0x76, 0x43, 0x22, 0xdf, 0xdc, 0x23, 0x94, 0xfb, 0x61, 0x20, 0xed, 0xe6, 0x03, 0x67, 0x1a,
	0xd2, 0x09, 0x1d, 0x13, 0x5f, 0x59, 0xf0, 0x31, 0xec, 0x0f, 0x19, 0x1f, 0x50, 0x1a, 0xce, 0x03,
	0x6e, 0xb3, 0x3f, 0xe6, 0x2c, 0xe1, 0xc8, 0x80, 0x16, 0x71, 0xdd, 0x98, 0x25, 0x89, 0xb1, 0xf5,
	0x74, 0xeb, 0x45, 0xc7, 0xce, 0x8e, 0xf8, 0x12, 0x90, 0xee, 0x9e, 0x44, 0x61, 0x90, 0x30, 0xf4,
	0x25, 0xec, 0x12, 0x69, 0xfa, 0x9e, 0x71, 0x22, 0x30, 0xbb, 0x27, 0x8f, 0x7a, 0x22, 0x09, 0xbe,
	0x88, 0x58, 0xd2, 0x1b, 0xe4, 0xd7, 0xb6, 0xee, 0x8b, 0xff, 0xd9, 0x56, 0x09, 0xa4, 0x59, 0x26,
	0x59, 0x02, 0x6f, 0xa1, 0xe5, 0x2c, 0x46, 0x81, 0xcb, 0x6e, 0x14, 0x19, 0xee, 0x65, 0x15, 0xf5,
	0x72, 0x6f, 0x4b, 0xba, 0x28, 0xd0, 0x79, 0xcd, 0xce, 0x40, 0xe8, 0x0d, 0x34, 0x9d, 0xc5, 0x39,
	0x49, 0xc6, 0xc6, 0xb6, 0x80, 0x3f, 0x2d, 0x81, 0x5b, 0xc2, 0x21, 0x07, 0x2b, 0x04, 0x7a, 0x9b,
	0x62, 0x07, 0xae, 0x1b, 0x1b, 0x75, 0x81, 0x7d, 0x56, 0x1e, 0x7a, 0x20, 0x3b, 0x52, 0xc0, 0xa7,
	0x36, 0xf4, 0x0b, 0xec, 0xcf, 0x03, 0x1a, 0x06, 0xbf, 0xf9, 0xf1, 0x8c, 0xb9, 0xd2, 0xd1, 0x68,
	0x08, 0xaa, 0x7e, 0x81, 0xea, 0x87, 0xdc, 0xab, 0x9a, 0x75, 0x9d, 0x0b, 0xbd, 0x81, 0x1d, 0x67,
	0x61, 0x4d, 0x27, 0xc6, 0xce, 0xa6, 0xd6, 0x58, 0xe9, 0xa4, 0x73, 0x1e, 0x09, 0xb1, 0xda, 0xd0,
	0x9c, 0x86, 0xe1, 0x64, 0x1e, 0xe1, 0x33, 0x30, 0xaa, 0x3a, 0x89, 0xba, 0xb0, 0x93, 0x70, 0x12,
	0x73, 0xd1, 0xfc, 0x86, 0x2d, 0x0f, 0xa9, 0x55, 0xcc, 0x4d, 0xf4, 0xb4, 0x61, 0xcb, 0x03, 0xfe,
	0x19, 0x1e, 0x96, 0xb7, 0x14, 0x1d, 0x01, 0xc8, 0xe5, 0x13, 0x83, 0x90, 0x8b, 0xa4, 0x59, 0x10,
	0x86, 0x3d, 0x3a, 0x66, 0x74, 0x72, 0xc5, 0x02, 0xd7, 0x0f, 0x3c, 0x41, 0xdb, 0xb6, 0x0b, 0x36,
	0xec, 0x80, 0x59, 0xdd, 0xf4, 0xea, 0x3d, 0xcd, 0x2b, 0xd8, 0x2e, 0xad, 0xa0, 0xae, 0x57, 0x30,
	0x83, 0xe7, 0xff, 0x69, 0x1a, 0xff, 0x53, 0xb8, 0x5f, 0x8b, 0x8d, 0xd7, 0xe7, 0x94, 0x46, 0x70,
	0xa6, 0x13, 0xad, 0x5f, 0xd9, 0xf1, 0x4e, 0x11, 0x2c, 0x25, 0x52, 0x25, 0x29, 0x25, 0xd2, 0x4f,
	0xa0, 0x25, 0x9b, 0x9f, 0x66, 0x5f, 0x7f, 0xb1, 0x7b, 0x82, 0x8a, 0x02, 0x4d, 0xaf, 0xec, 0xcc,
	0x05, 0xff, 0xbd, 0x05, 0xdd, 0x21, 0xe3, 0x22, 0xbb, 0x54, 0xa8, 0xcb, 0x26, 0x0c, 0x56, 0xa5,
	0xf9, 0xbc, 0xb0, 0x7f, 0x39, 0xa0, 0x5a, 0x9d, 0x5f, 0xaf, 0xa8, 0xf3, 0xa3, 0x72, 0x86, 0x0a,
	0x81, 0x6a, 0x3b, 0x3c, 0x82, 0xc7, 0x1b, 0x42, 0xde, 0x69, 0x8d, 0x5f, 0xc3, 0x7b, 0x95, 0xb1,
	0xab, 0xc7, 0x82, 0xbf, 0x83, 0xc3, 0x95, 0x2e, 0xa9, 0x6e, 0x7f, 0x06, 0x6d, 0x67, 0x2a, 0x6d,
	0xaa, 0xdd, 0x87, 0x7a, 0xbb, 0x97, 0x08, 0x7b, 0xe9, 0x86, 0x0f, 0xe1, 0x60, 0xc8, 0xf8, 0x69,
	0xfa, 0x38, 0x8b, 0x1b, 0x19, 0x1c, 0x5f, 0x88, 0x41, 0x68, 0x66, 0x15, 0xe1, 0x15, 0x74, 0x68,
	0x66, 0x54, 0xa3, 0x28, 0x84, 0xc8, 0x11, 0xb9, 0x1f, 0xfe, 0x06, 0xf6, 0xaf, 0x59, 0xa0, 0x36,
	0x3c, 0x2b, 0xef, 0x25, 0x34, 0xe5, 0xd8, 0x15, 0x4d, 0xd9, 0x62, 0x28, 0x0f, 0xdc, 0x05, 0xa4,
	0x13, 0xc8, 0x5c, 0xf0, 0x57, 0xa2, 0x7b, 0x36, 0xa3, 0xcc, 0x8f, 0xb8, 0xb5, 0x28, 0xd2, 0xdf,
	0xf2, 0x0e, 0xe0, 0x0b, 0xa1, 0xf1, 0x35, 0xb0, 0x2a, 0xf3, 0x18, 0x5a, 0xb1, 0xbc, 0x52, 0xd9,
	0x1d, 0xe8, 0xd9, 0x29, 0x94, 0x9d, 0xf9, 0xe0, 0x01, 0x1c, 0xd8, 0x8c, 0xb8, 0xa7, 0x61, 0xc0,
	0x63, 0x42, 0xf9, 0x7d, 0x4a, 0x7c, 0x09, 0xdd, 0x22, 0x85, 0xca, 0x04, 0x41, 0xc3, 0x25, 0xaa,
	0xd7, 0x1d, 0x5b, 0xfc, 0xc6, 0x06, 0x3c, 0xbc, 0x9e, 0x7b, 0x1e, 0x4b, 0xf8, 0x90, 0x24, 0x57,
	0xb1, 0x4f, 0x59, 0x36, 0xb6, 0xd7, 0xf0, 0x68, 0xed, 0x46, 0x11, 0x99, 0xd0, 0xf6, 0x94, 0x4d,
	0xad, 0xe6, 0xf2, 0x9c, 0xae, 0xf4, 0xb7, 0x09, 0xf7, 0x67, 0x84, 0xb3, 0x21, 0x49, 0xce, 0xc2,
	0xf8, 0xfe, 0xa3, 0xfa, 0x14, 0x9e, 0x94, 0x53, 0xa9, 0x34, 0x1e, 0x40, 0xdd, 0x23, 0x89, 0xca,
	0x20, 0xfd, 0x79, 0xf2, 0x57, 0x13, 0x60, 0x70, 0x35, 0xba, 0x66, 0xf1, 0x9f, 0x3e, 0x65, 0x68,
	0x04, 0x90, 0x7f, 0xec, 0xd1, 0xe3, 0x95, 0xef, 0x8c, 0xfe, 0x8f, 0xc1, 0x7c, 0x52, 0x7e, 0xa9,
	0xd6, 0xa3, 0xb6, 0xa4, 0x12, 0x8f, 0xcb, 0x1a, 0x95, 0xfe, 0xed, 0x5f, 0xa3, 0x2a, 0xbc, 0x62,
	0xb8, 0x86, 0x6c, 0x78, 0xa7, 0x20, 0x39, 0x74, 0x54, 0xf1, 0x00, 0x65, 0x84, 0x1f, 0x54, 0xde,
	0x2f, 0x39, 0x2f, 0x61, 0x4f, 0xd7, 0x18, 0x7a, 0xbf, 0x00, 0x59, 0x95, 0xa4, 0x79, 0x54, 0x75,
	0xad, 0xd7, 0x9b, 0xcb, 0x44, 0xaf, 0x77, 0x4d, 0x7d, 0x7a, 0xbd, 0x25, 0xca, 0xaa, 0x21, 0x22,
	0x5e, 0xf3, 0x15, 0x79, 0xa0, 0xe2, 0x9b, 0x59, 0xae, 0x3c, 0xf3, 0xd9, 0x66, 0x27, 0xbd, 0x7c,
	0x7d, 0xe3, 0xf5, 0xf2, 0x4b, 0xc4, 0xa4, 0x97, 0x5f, 0x26, 0x14, 0x5c, 0x43, 0x3f, 0xc2, 0xbb,
	0x2b, 0xcb, 0x8f, 0xb4, 0xbf, 0x60, 0xe5, 0x8a, 0x31, 0x3f, 0xdc, 0xe0, 0xb1, 0x64, 0xf6, 0xa0,
	0x5b, 0xb6, 0xd4, 0x48, 0xfb, 0x0a, 0x6d, 0xd0, 0x8f, 0xf9, 0xf1, 0x6d, 0x6e, 0x59, 0x20, 0xeb,
	0x8b, 0x9f, 0x3e, 0xf7, 0x7c, 0x3e, 0x9e, 0x3b, 0x3d, 0x1a, 0xce, 0xfa, 0x02, 0x15, 0xc5, 0xe1,
	0xef, 0x8c, 0x72, 0x79, 0x38, 0xa6, 0x61, 0xcc, 0xfa, 0xe2, 0x4f, 0xb4, 0xc7, 0x82, 0x7e, 0x46,
	0xeb, 0x34, 0x85, 0xe9, 0xd5, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xe5, 0xf9, 0x5f, 0x8e,
	0x0b, 0x00, 0x00,
}
