// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blockchain.proto

package iotextypes // import "github.com/iotexproject/iotex-core/protogen/iotextypes"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// header of a block
type BlockHeaderPb struct {
	Version              uint32               `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ChainID              uint32               `protobuf:"varint,2,opt,name=chainID,proto3" json:"chainID,omitempty"`
	Height               uint64               `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PrevBlockHash        []byte               `protobuf:"bytes,5,opt,name=prevBlockHash,proto3" json:"prevBlockHash,omitempty"`
	TxRoot               []byte               `protobuf:"bytes,6,opt,name=txRoot,proto3" json:"txRoot,omitempty"`
	StateRoot            []byte               `protobuf:"bytes,7,opt,name=stateRoot,proto3" json:"stateRoot,omitempty"`
	DeltaStateDigest     []byte               `protobuf:"bytes,8,opt,name=deltaStateDigest,proto3" json:"deltaStateDigest,omitempty"`
	ReceiptRoot          []byte               `protobuf:"bytes,9,opt,name=receiptRoot,proto3" json:"receiptRoot,omitempty"`
	Reserved             []byte               `protobuf:"bytes,10,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Signature            []byte               `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
	Pubkey               []byte               `protobuf:"bytes,12,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BlockHeaderPb) Reset()         { *m = BlockHeaderPb{} }
func (m *BlockHeaderPb) String() string { return proto.CompactTextString(m) }
func (*BlockHeaderPb) ProtoMessage()    {}
func (*BlockHeaderPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_afb816c206c9a094, []int{0}
}
func (m *BlockHeaderPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeaderPb.Unmarshal(m, b)
}
func (m *BlockHeaderPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeaderPb.Marshal(b, m, deterministic)
}
func (dst *BlockHeaderPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeaderPb.Merge(dst, src)
}
func (m *BlockHeaderPb) XXX_Size() int {
	return xxx_messageInfo_BlockHeaderPb.Size(m)
}
func (m *BlockHeaderPb) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeaderPb.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeaderPb proto.InternalMessageInfo

func (m *BlockHeaderPb) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BlockHeaderPb) GetChainID() uint32 {
	if m != nil {
		return m.ChainID
	}
	return 0
}

func (m *BlockHeaderPb) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockHeaderPb) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *BlockHeaderPb) GetPrevBlockHash() []byte {
	if m != nil {
		return m.PrevBlockHash
	}
	return nil
}

func (m *BlockHeaderPb) GetTxRoot() []byte {
	if m != nil {
		return m.TxRoot
	}
	return nil
}

func (m *BlockHeaderPb) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *BlockHeaderPb) GetDeltaStateDigest() []byte {
	if m != nil {
		return m.DeltaStateDigest
	}
	return nil
}

func (m *BlockHeaderPb) GetReceiptRoot() []byte {
	if m != nil {
		return m.ReceiptRoot
	}
	return nil
}

func (m *BlockHeaderPb) GetReserved() []byte {
	if m != nil {
		return m.Reserved
	}
	return nil
}

func (m *BlockHeaderPb) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *BlockHeaderPb) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

// footer of a block
type BlockFooterPb struct {
	CommitTimestamp      int64           `protobuf:"varint,1,opt,name=CommitTimestamp,proto3" json:"CommitTimestamp,omitempty"`
	Endorsements         *EndorsementSet `protobuf:"bytes,2,opt,name=endorsements,proto3" json:"endorsements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BlockFooterPb) Reset()         { *m = BlockFooterPb{} }
func (m *BlockFooterPb) String() string { return proto.CompactTextString(m) }
func (*BlockFooterPb) ProtoMessage()    {}
func (*BlockFooterPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_afb816c206c9a094, []int{1}
}
func (m *BlockFooterPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockFooterPb.Unmarshal(m, b)
}
func (m *BlockFooterPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockFooterPb.Marshal(b, m, deterministic)
}
func (dst *BlockFooterPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockFooterPb.Merge(dst, src)
}
func (m *BlockFooterPb) XXX_Size() int {
	return xxx_messageInfo_BlockFooterPb.Size(m)
}
func (m *BlockFooterPb) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockFooterPb.DiscardUnknown(m)
}

var xxx_messageInfo_BlockFooterPb proto.InternalMessageInfo

func (m *BlockFooterPb) GetCommitTimestamp() int64 {
	if m != nil {
		return m.CommitTimestamp
	}
	return 0
}

func (m *BlockFooterPb) GetEndorsements() *EndorsementSet {
	if m != nil {
		return m.Endorsements
	}
	return nil
}

// block consists of header followed by transactions
// hash of current block can be computed from header hence not stored
type BlockPb struct {
	Header               *BlockHeaderPb `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Actions              []*ActionPb    `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	Footer               *BlockFooterPb `protobuf:"bytes,3,opt,name=footer,proto3" json:"footer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockPb) Reset()         { *m = BlockPb{} }
func (m *BlockPb) String() string { return proto.CompactTextString(m) }
func (*BlockPb) ProtoMessage()    {}
func (*BlockPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_afb816c206c9a094, []int{2}
}
func (m *BlockPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockPb.Unmarshal(m, b)
}
func (m *BlockPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockPb.Marshal(b, m, deterministic)
}
func (dst *BlockPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockPb.Merge(dst, src)
}
func (m *BlockPb) XXX_Size() int {
	return xxx_messageInfo_BlockPb.Size(m)
}
func (m *BlockPb) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockPb.DiscardUnknown(m)
}

var xxx_messageInfo_BlockPb proto.InternalMessageInfo

func (m *BlockPb) GetHeader() *BlockHeaderPb {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BlockPb) GetActions() []*ActionPb {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *BlockPb) GetFooter() *BlockFooterPb {
	if m != nil {
		return m.Footer
	}
	return nil
}

// Receipts consists of a collection of recepit
type Receipts struct {
	Receipts             []*ReceiptPb `protobuf:"bytes,1,rep,name=receipts,proto3" json:"receipts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Receipts) Reset()         { *m = Receipts{} }
func (m *Receipts) String() string { return proto.CompactTextString(m) }
func (*Receipts) ProtoMessage()    {}
func (*Receipts) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_afb816c206c9a094, []int{3}
}
func (m *Receipts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipts.Unmarshal(m, b)
}
func (m *Receipts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipts.Marshal(b, m, deterministic)
}
func (dst *Receipts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipts.Merge(dst, src)
}
func (m *Receipts) XXX_Size() int {
	return xxx_messageInfo_Receipts.Size(m)
}
func (m *Receipts) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipts.DiscardUnknown(m)
}

var xxx_messageInfo_Receipts proto.InternalMessageInfo

func (m *Receipts) GetReceipts() []*ReceiptPb {
	if m != nil {
		return m.Receipts
	}
	return nil
}

// Candidates and list of candidates
type Candidate struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Votes                []byte   `protobuf:"bytes,2,opt,name=votes,proto3" json:"votes,omitempty"`
	PubKey               []byte   `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	CreationHeight       uint64   `protobuf:"varint,4,opt,name=creationHeight,proto3" json:"creationHeight,omitempty"`
	LastUpdateHeight     uint64   `protobuf:"varint,5,opt,name=lastUpdateHeight,proto3" json:"lastUpdateHeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candidate) Reset()         { *m = Candidate{} }
func (m *Candidate) String() string { return proto.CompactTextString(m) }
func (*Candidate) ProtoMessage()    {}
func (*Candidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_afb816c206c9a094, []int{4}
}
func (m *Candidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidate.Unmarshal(m, b)
}
func (m *Candidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidate.Marshal(b, m, deterministic)
}
func (dst *Candidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidate.Merge(dst, src)
}
func (m *Candidate) XXX_Size() int {
	return xxx_messageInfo_Candidate.Size(m)
}
func (m *Candidate) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidate.DiscardUnknown(m)
}

var xxx_messageInfo_Candidate proto.InternalMessageInfo

func (m *Candidate) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Candidate) GetVotes() []byte {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *Candidate) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Candidate) GetCreationHeight() uint64 {
	if m != nil {
		return m.CreationHeight
	}
	return 0
}

func (m *Candidate) GetLastUpdateHeight() uint64 {
	if m != nil {
		return m.LastUpdateHeight
	}
	return 0
}

type CandidateList struct {
	Candidates           []*Candidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CandidateList) Reset()         { *m = CandidateList{} }
func (m *CandidateList) String() string { return proto.CompactTextString(m) }
func (*CandidateList) ProtoMessage()    {}
func (*CandidateList) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_afb816c206c9a094, []int{5}
}
func (m *CandidateList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateList.Unmarshal(m, b)
}
func (m *CandidateList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateList.Marshal(b, m, deterministic)
}
func (dst *CandidateList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateList.Merge(dst, src)
}
func (m *CandidateList) XXX_Size() int {
	return xxx_messageInfo_CandidateList.Size(m)
}
func (m *CandidateList) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateList.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateList proto.InternalMessageInfo

func (m *CandidateList) GetCandidates() []*Candidate {
	if m != nil {
		return m.Candidates
	}
	return nil
}

// Blockchain Metadata
type ChainMeta struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Supply               string   `protobuf:"bytes,2,opt,name=supply,proto3" json:"supply,omitempty"`
	NumActions           int64    `protobuf:"varint,3,opt,name=numActions,proto3" json:"numActions,omitempty"`
	Tps                  int64    `protobuf:"varint,4,opt,name=tps,proto3" json:"tps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainMeta) Reset()         { *m = ChainMeta{} }
func (m *ChainMeta) String() string { return proto.CompactTextString(m) }
func (*ChainMeta) ProtoMessage()    {}
func (*ChainMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_afb816c206c9a094, []int{6}
}
func (m *ChainMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainMeta.Unmarshal(m, b)
}
func (m *ChainMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainMeta.Marshal(b, m, deterministic)
}
func (dst *ChainMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainMeta.Merge(dst, src)
}
func (m *ChainMeta) XXX_Size() int {
	return xxx_messageInfo_ChainMeta.Size(m)
}
func (m *ChainMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ChainMeta proto.InternalMessageInfo

func (m *ChainMeta) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ChainMeta) GetSupply() string {
	if m != nil {
		return m.Supply
	}
	return ""
}

func (m *ChainMeta) GetNumActions() int64 {
	if m != nil {
		return m.NumActions
	}
	return 0
}

func (m *ChainMeta) GetTps() int64 {
	if m != nil {
		return m.Tps
	}
	return 0
}

// Block Metadata
type BlockMeta struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Height               uint64   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NumActions           int64    `protobuf:"varint,4,opt,name=numActions,proto3" json:"numActions,omitempty"`
	ProducerAddress      string   `protobuf:"bytes,5,opt,name=producerAddress,proto3" json:"producerAddress,omitempty"`
	TransferAmount       string   `protobuf:"bytes,6,opt,name=transferAmount,proto3" json:"transferAmount,omitempty"`
	TxRoot               string   `protobuf:"bytes,7,opt,name=txRoot,proto3" json:"txRoot,omitempty"`
	ReceiptRoot          string   `protobuf:"bytes,8,opt,name=receiptRoot,proto3" json:"receiptRoot,omitempty"`
	DeltaStateDigest     string   `protobuf:"bytes,9,opt,name=deltaStateDigest,proto3" json:"deltaStateDigest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockMeta) Reset()         { *m = BlockMeta{} }
func (m *BlockMeta) String() string { return proto.CompactTextString(m) }
func (*BlockMeta) ProtoMessage()    {}
func (*BlockMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_afb816c206c9a094, []int{7}
}
func (m *BlockMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMeta.Unmarshal(m, b)
}
func (m *BlockMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMeta.Marshal(b, m, deterministic)
}
func (dst *BlockMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMeta.Merge(dst, src)
}
func (m *BlockMeta) XXX_Size() int {
	return xxx_messageInfo_BlockMeta.Size(m)
}
func (m *BlockMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMeta.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMeta proto.InternalMessageInfo

func (m *BlockMeta) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BlockMeta) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockMeta) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockMeta) GetNumActions() int64 {
	if m != nil {
		return m.NumActions
	}
	return 0
}

func (m *BlockMeta) GetProducerAddress() string {
	if m != nil {
		return m.ProducerAddress
	}
	return ""
}

func (m *BlockMeta) GetTransferAmount() string {
	if m != nil {
		return m.TransferAmount
	}
	return ""
}

func (m *BlockMeta) GetTxRoot() string {
	if m != nil {
		return m.TxRoot
	}
	return ""
}

func (m *BlockMeta) GetReceiptRoot() string {
	if m != nil {
		return m.ReceiptRoot
	}
	return ""
}

func (m *BlockMeta) GetDeltaStateDigest() string {
	if m != nil {
		return m.DeltaStateDigest
	}
	return ""
}

// Account Metadata
type AccountMeta struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance              string   `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Nonce                uint64   `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	PendingNonce         uint64   `protobuf:"varint,4,opt,name=pendingNonce,proto3" json:"pendingNonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountMeta) Reset()         { *m = AccountMeta{} }
func (m *AccountMeta) String() string { return proto.CompactTextString(m) }
func (*AccountMeta) ProtoMessage()    {}
func (*AccountMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_afb816c206c9a094, []int{8}
}
func (m *AccountMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountMeta.Unmarshal(m, b)
}
func (m *AccountMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountMeta.Marshal(b, m, deterministic)
}
func (dst *AccountMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountMeta.Merge(dst, src)
}
func (m *AccountMeta) XXX_Size() int {
	return xxx_messageInfo_AccountMeta.Size(m)
}
func (m *AccountMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountMeta.DiscardUnknown(m)
}

var xxx_messageInfo_AccountMeta proto.InternalMessageInfo

func (m *AccountMeta) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AccountMeta) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *AccountMeta) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *AccountMeta) GetPendingNonce() uint64 {
	if m != nil {
		return m.PendingNonce
	}
	return 0
}

func init() {
	proto.RegisterType((*BlockHeaderPb)(nil), "iotextypes.BlockHeaderPb")
	proto.RegisterType((*BlockFooterPb)(nil), "iotextypes.BlockFooterPb")
	proto.RegisterType((*BlockPb)(nil), "iotextypes.BlockPb")
	proto.RegisterType((*Receipts)(nil), "iotextypes.Receipts")
	proto.RegisterType((*Candidate)(nil), "iotextypes.Candidate")
	proto.RegisterType((*CandidateList)(nil), "iotextypes.CandidateList")
	proto.RegisterType((*ChainMeta)(nil), "iotextypes.ChainMeta")
	proto.RegisterType((*BlockMeta)(nil), "iotextypes.BlockMeta")
	proto.RegisterType((*AccountMeta)(nil), "iotextypes.AccountMeta")
}

func init() { proto.RegisterFile("blockchain.proto", fileDescriptor_blockchain_afb816c206c9a094) }

var fileDescriptor_blockchain_afb816c206c9a094 = []byte{
	// 774 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0x51, 0x8f, 0xe3, 0x34,
	0x10, 0x56, 0xb6, 0xdd, 0x6d, 0x33, 0xed, 0x72, 0x8b, 0x75, 0x9c, 0xc2, 0xea, 0x04, 0x55, 0x84,
	0x50, 0x85, 0x44, 0x57, 0x2c, 0x02, 0xdd, 0x0b, 0x48, 0xbd, 0x3d, 0x4e, 0x87, 0x0e, 0x50, 0xe5,
	0x83, 0x17, 0xde, 0x9c, 0x64, 0x36, 0x0d, 0xd7, 0xc4, 0x91, 0xed, 0x54, 0x5b, 0xf1, 0x2b, 0xf8,
	0x05, 0x3c, 0xf2, 0xc4, 0x7f, 0x44, 0x1e, 0x3b, 0x6d, 0xd2, 0x2e, 0x6f, 0x9d, 0x6f, 0xbe, 0x78,
	0x3e, 0xcf, 0x7c, 0x9e, 0xc2, 0x55, 0xb2, 0x91, 0xe9, 0xfb, 0x74, 0x2d, 0x8a, 0x6a, 0x51, 0x2b,
	0x69, 0x24, 0x83, 0x42, 0x1a, 0x7c, 0x30, 0xbb, 0x1a, 0xf5, 0xf5, 0x54, 0xa4, 0xa6, 0x90, 0x3e,
	0x73, 0xfd, 0x21, 0x56, 0x99, 0x54, 0x1a, 0x4b, 0xac, 0x8c, 0x87, 0x3e, 0xcd, 0xa5, 0xcc, 0x37,
	0x78, 0x43, 0x51, 0xd2, 0xdc, 0xdf, 0x98, 0xa2, 0x44, 0x6d, 0x44, 0x59, 0x3b, 0x42, 0xfc, 0xd7,
	0x00, 0x2e, 0x5f, 0xda, 0x12, 0x6f, 0x50, 0x64, 0xa8, 0x56, 0x09, 0x8b, 0x60, 0xb4, 0x45, 0xa5,
	0x0b, 0x59, 0x45, 0xc1, 0x2c, 0x98, 0x5f, 0xf2, 0x36, 0xb4, 0x19, 0x12, 0xf2, 0xe3, 0xab, 0xe8,
	0xcc, 0x65, 0x7c, 0xc8, 0x9e, 0xc1, 0xc5, 0x1a, 0x8b, 0x7c, 0x6d, 0xa2, 0xc1, 0x2c, 0x98, 0x0f,
	0xb9, 0x8f, 0xd8, 0x0b, 0x08, 0xf7, 0x05, 0xa3, 0xe1, 0x2c, 0x98, 0x4f, 0x6e, 0xaf, 0x17, 0x4e,
	0xd2, 0xa2, 0x95, 0xb4, 0xf8, 0xb5, 0x65, 0xf0, 0x03, 0x99, 0x7d, 0x06, 0x97, 0xb5, 0xc2, 0xad,
	0x93, 0x26, 0xf4, 0x3a, 0x3a, 0x9f, 0x05, 0xf3, 0x29, 0xef, 0x83, 0xb6, 0xae, 0x79, 0xe0, 0x52,
	0x9a, 0xe8, 0x82, 0xd2, 0x3e, 0x62, 0xcf, 0x21, 0xd4, 0x46, 0x18, 0xa4, 0xd4, 0x88, 0x52, 0x07,
	0x80, 0x7d, 0x01, 0x57, 0x19, 0x6e, 0x8c, 0x78, 0x67, 0x91, 0x57, 0x45, 0x8e, 0xda, 0x44, 0x63,
	0x22, 0x9d, 0xe0, 0x6c, 0x06, 0x13, 0x85, 0x29, 0x16, 0xb5, 0xa1, 0xb3, 0x42, 0xa2, 0x75, 0x21,
	0x76, 0x0d, 0x63, 0x85, 0x1a, 0xd5, 0x16, 0xb3, 0x08, 0x28, 0xbd, 0x8f, 0x49, 0x47, 0x91, 0x57,
	0xc2, 0x34, 0x0a, 0xa3, 0x89, 0xd7, 0xd1, 0x02, 0x56, 0x7d, 0xdd, 0x24, 0xef, 0x71, 0x17, 0x4d,
	0x9d, 0x7a, 0x17, 0xc5, 0x3b, 0x3f, 0x92, 0xd7, 0x52, 0x1a, 0x1a, 0xc9, 0x1c, 0x9e, 0xdc, 0xc9,
	0xb2, 0x2c, 0xcc, 0xbe, 0x55, 0x34, 0x9a, 0x01, 0x3f, 0x86, 0xd9, 0xf7, 0x30, 0xed, 0x98, 0x40,
	0xd3, 0x9c, 0x6c, 0xcf, 0x0f, 0x9e, 0x59, 0xfc, 0x70, 0xc8, 0xbf, 0x43, 0xc3, 0x7b, 0xfc, 0xf8,
	0xef, 0x00, 0x46, 0x54, 0x7b, 0x95, 0xb0, 0xaf, 0xec, 0x50, 0xad, 0x29, 0xa8, 0xd8, 0xe4, 0xf6,
	0xe3, 0xee, 0x29, 0x3d, 0xcf, 0x70, 0x4f, 0x64, 0x0b, 0x18, 0x39, 0x47, 0xda, 0xca, 0x83, 0xf9,
	0xe4, 0xf6, 0x69, 0xf7, 0x9b, 0x25, 0xa5, 0x56, 0x09, 0x6f, 0x49, 0xb6, 0xc4, 0x3d, 0x5d, 0x92,
	0x7c, 0xf3, 0x58, 0x89, 0xb6, 0x07, 0xdc, 0x13, 0xe3, 0xef, 0x60, 0xcc, 0x5d, 0xf7, 0xed, 0xe7,
	0x63, 0x3f, 0x09, 0x1d, 0x05, 0x54, 0xef, 0xa3, 0xee, 0x01, 0x9e, 0xb7, 0x4a, 0xf8, 0x9e, 0x16,
	0xff, 0x13, 0x40, 0x78, 0x27, 0xaa, 0xac, 0xc8, 0x84, 0x41, 0xeb, 0x68, 0x91, 0x65, 0x0a, 0xb5,
	0xa6, 0x3b, 0x86, 0xbc, 0x0d, 0xd9, 0x53, 0x38, 0xdf, 0x4a, 0x83, 0xae, 0x83, 0x53, 0xee, 0x02,
	0x3f, 0xb1, 0xb7, 0xb8, 0x23, 0xbd, 0x6e, 0x62, 0x6f, 0x71, 0xc7, 0x3e, 0x87, 0x0f, 0x52, 0x85,
	0xc2, 0x5e, 0xea, 0x8d, 0x7b, 0x07, 0x43, 0x7a, 0x07, 0x47, 0xa8, 0x75, 0xde, 0x46, 0x68, 0xf3,
	0x5b, 0x6d, 0xab, 0x7b, 0xe6, 0x39, 0x31, 0x4f, 0xf0, 0xf8, 0x35, 0x5c, 0xee, 0x85, 0xfe, 0x54,
	0x68, 0xc3, 0xbe, 0x01, 0x48, 0x5b, 0xe0, 0xd1, 0xfb, 0xee, 0xe9, 0xbc, 0x43, 0x8c, 0x4b, 0x08,
	0xef, 0xec, 0x33, 0xfd, 0x19, 0x8d, 0xe8, 0x3c, 0xd4, 0xa0, 0xf7, 0x50, 0x9f, 0xc1, 0x85, 0x6e,
	0xea, 0x7a, 0xb3, 0xa3, 0xfb, 0x86, 0xdc, 0x47, 0xec, 0x13, 0x80, 0xaa, 0x29, 0x97, 0x7e, 0xa6,
	0x03, 0x32, 0x5d, 0x07, 0x61, 0x57, 0x30, 0x30, 0xb5, 0xa6, 0xdb, 0x0e, 0xb8, 0xfd, 0x19, 0xff,
	0x7b, 0x06, 0x21, 0x4d, 0x8e, 0xea, 0x31, 0x18, 0xae, 0xed, 0xeb, 0x75, 0xdd, 0xa5, 0xdf, 0x1d,
	0x0d, 0x67, 0x3d, 0x0d, 0xcf, 0xbb, 0xcb, 0xc2, 0x95, 0xea, 0x2c, 0x84, 0xbe, 0x92, 0xe1, 0x89,
	0x92, 0x39, 0x3c, 0xa9, 0x95, 0xcc, 0x9a, 0x14, 0xd5, 0xd2, 0x8f, 0xf4, 0x9c, 0x8a, 0x1e, 0xc3,
	0x76, 0x58, 0x46, 0x89, 0x4a, 0xdf, 0xa3, 0x5a, 0x96, 0xb2, 0xa9, 0xdc, 0xf2, 0x08, 0xf9, 0x11,
	0xda, 0x59, 0x2e, 0x23, 0xd7, 0x13, 0xbf, 0x5c, 0x8e, 0x56, 0xc2, 0x98, 0x92, 0xbd, 0x95, 0xf0,
	0xd8, 0x82, 0x09, 0x89, 0x76, 0x82, 0xc7, 0x7f, 0xc2, 0x64, 0x99, 0xa6, 0xb6, 0x20, 0x35, 0xec,
	0xff, 0x1d, 0x19, 0xc1, 0x28, 0x11, 0x1b, 0x51, 0xa5, 0xe8, 0x67, 0xd4, 0x86, 0xd6, 0xab, 0x95,
	0xb4, 0xb8, 0x5b, 0xbe, 0x2e, 0x60, 0x31, 0x4c, 0x6b, 0xac, 0xb2, 0xa2, 0xca, 0x7f, 0xa1, 0xa4,
	0x73, 0x64, 0x0f, 0x7b, 0xf9, 0xe2, 0xf7, 0x6f, 0xf3, 0xc2, 0xac, 0x9b, 0x64, 0x91, 0xca, 0xf2,
	0x86, 0xac, 0x54, 0x2b, 0xf9, 0x07, 0xa6, 0xc6, 0x05, 0x5f, 0xa6, 0x52, 0xf9, 0x3f, 0x8f, 0x1c,
	0xab, 0x9b, 0x83, 0xd7, 0x92, 0x0b, 0x02, 0xbf, 0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xa5,
	0xa5, 0x31, 0xa0, 0x06, 0x00, 0x00,
}
