network:
  externalHost: 12.34.56.78
  externalPort: 4689
  bootstrapNodes:
    - /dns4/bootnode-0.mainnet.iotex.one/tcp/4689/p2p/12D3KooWPfQDF8ASjd4r7jS9e7F1wn6zod7Mf4ERr8etoY6ctQp5
    - /dns4/bootnode-1.mainnet.iotex.one/tcp/4689/p2p/12D3KooWN4TQ1CWRA7yvJdQCdti1qARLXXu2UEHJfycn3XbnAnRh
    - /dns4/bootnode-2.mainnet.iotex.one/tcp/4689/p2p/12D3KooWSiktocuUke16bPoW9zrLawEBaEc1UriaPRwm82xbr2BQ
    - /dns4/bootnode-3.mainnet.iotex.one/tcp/4689/p2p/12D3KooWEsmwaorbZX3HRCnhkMPjMAHzwu3om1pdGrtVm2QaM35n

chain:
  # If you are a delegate, make sure producerPrivKey is the key for the operator address you have registered.
  producerPrivKey: 96f0aa5e8523d6a28dc35c927274be4e931e74eaa720b418735debfcbfe712b8
  chainDBPath: /var/data/chain.db
  trieDBPath: /var/data/trie.db
  maxCacheSize: 1000
  committee:
    gravityChainAPIs:
      - https://mainnet.infura.io/v3/b355cae6fafc4302b106b937ee6c15af
      - wss://us-east-1.iotex.world/ws
      - wss://singapore-1.iotex.world/ws
      - wss://tokyo-1.iotex.world/ws
      - wss://paris-1.iotex.world/ws
      - wss://us-west-1.iotex.world/ws
      - wss://sydney-1.iotex.world/ws
    numOfRetries: 20
    paginationSize: 11
    cacheSize: 1000
  gravityChainDB:
    dbPath: /var/data/poll.db
    numRetries: 8

actPool:
  minGasPrice: "1000000000000"

api:
  gasStation:
    defaultGas: 1000000000000

consensus:
  scheme: ROLLDPOS
  rollDPoS:
    fsm:
      unmatchedEventTTL: 3s
      unmatchedEventInterval: 100ms
      acceptBlockTTL: 4s
      acceptProposalEndorsementTTL: 2s
      acceptLockEndorsementTTL: 2s
    delay: 10s

blockSync:
  bufferSize: 400
  maxRepeat: 3
  repeatDecayStep: 3

log:
  zap:
    level: info
    encoding: json
    disableStacktrace: true
    outputPaths: ["stderr", "stdout"]
    errorOutputPaths: ["stderr"]
  stderrRedirectFile: /var/log/s.log
  stdLogRedirect: true
