actPool:
  minGasPrice: "0"
  store:
    datadir: ./data3/actionstore.cache
chain:
  bloomfilterIndexDBPath: ./data3/bloomfilter.index.db
  candidateIndexDBPath: ./data3/candidate.index.db
  chainDBPath: ./data3/chain.db
  committee:
    cacheSize: 1000
    gravityChainAPIs:
    - https://kovan.infura.io/v3/cdda4721e8c24107bde9d3ecff80a5b7
    numOfRetries: 20
    paginationSize: 255
  enableStakingIndexer: true
  enableStateDBCaching: true
  enableSystemLog: false
  gravityChainDB:
    dbPath: ./data3/poll.db
    numRetries: 8
  id: 3
  evmNetworkID: 4691
  indexDBPath: ./data3/index.db
  maxCacheSize: 1000
  contractStakingIndexDBPath: ./data3/contractstaking.index.db
  stakingIndexDBPath: ./data3/staking.index.db
  trieDBPath: ./data3/trie.db
  trieDBPatchFile: ""
  blobStoreDBPath: ./data3/blobstore.db
  blobStoreRetentionDays: 1
consensus:
  rollDPoS:
    consensusDBPath: ./data3/consensus.db
    delay: 30s
    fsm:
      acceptBlockTTL: 4s
      acceptLockEndorsementTTL: 2s
      acceptProposalEndorsementTTL: 2s
      eventChanSize: 100000
      unmatchedEventInterval: 100ms
      unmatchedEventTTL: 3s
  scheme: ROLLDPOS
log:
  ecsIntegration: false
  stdLogRedirect: false
  zap:
    development: true
    disableStacktrace: false
    encoding: json
    errorOutputPaths:
    - stderr
    level: info
    outputPaths:
    - stderr
    - stdout
network:
  bootstrapNodes:
  - /dns4/bootnode-0.nightly.iotex.one/tcp/4689/p2p/12D3KooWCb1nZdLsR6WBgXqmGnzRvhxASQJaAB3NgwTNk3JE43Wj
  enableRateLimit: false
system:
  httpAdminPort: 8082 
  systemLogDBPath: ./data3/systemlog.db
