account:
  initBalances:
    # overwrite with your test address
    io1ck66hvsyaz2k58a7e2zzughfmug7l8zvhywjhv: "100000000000000000000000000000000000"
blockchain:
  blockInterval: 5s
  numSubEpochs: 15
  timeBasedRotation: true
  # overwrite heights for testing needs
