// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulator.proto

/*
Package simulator is a generated protocol buffer package.

It is generated from these files:
	simulator.proto

It has these top-level messages:
	Request
	InitRequest
	Reply
	Proposal
	Empty
*/
package simulator

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the playerID and the value of the message being fed into the consensus engine
type Request struct {
	PlayerID        int32  `protobuf:"varint,1,opt,name=playerID" json:"playerID,omitempty"`
	InternalMsgType uint32 `protobuf:"varint,2,opt,name=internalMsgType" json:"internalMsgType,omitempty"`
	Value           string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetPlayerID() int32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *Request) GetInternalMsgType() uint32 {
	if m != nil {
		return m.InternalMsgType
	}
	return 0
}

func (m *Request) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// The request message telling the server to initialize the necessary parameters
type InitRequest struct {
	NPlayers int32 `protobuf:"varint,1,opt,name=nPlayers" json:"nPlayers,omitempty"`
}

func (m *InitRequest) Reset()                    { *m = InitRequest{} }
func (m *InitRequest) String() string            { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()               {}
func (*InitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InitRequest) GetNPlayers() int32 {
	if m != nil {
		return m.NPlayers
	}
	return 0
}

// The response message returning the output of the consensus engine
type Reply struct {
	MessageType     int32  `protobuf:"varint,1,opt,name=messageType" json:"messageType,omitempty"`
	InternalMsgType uint32 `protobuf:"varint,2,opt,name=internalMsgType" json:"internalMsgType,omitempty"`
	Value           string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Reply) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *Reply) GetInternalMsgType() uint32 {
	if m != nil {
		return m.InternalMsgType
	}
	return 0
}

func (m *Reply) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Proposal struct {
	PlayerID        int32  `protobuf:"varint,1,opt,name=playerID" json:"playerID,omitempty"`
	InternalMsgType uint32 `protobuf:"varint,2,opt,name=internalMsgType" json:"internalMsgType,omitempty"`
	Value           string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *Proposal) Reset()                    { *m = Proposal{} }
func (m *Proposal) String() string            { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()               {}
func (*Proposal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Proposal) GetPlayerID() int32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *Proposal) GetInternalMsgType() uint32 {
	if m != nil {
		return m.InternalMsgType
	}
	return 0
}

func (m *Proposal) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// an empty message
type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*Request)(nil), "simulator.Request")
	proto.RegisterType((*InitRequest)(nil), "simulator.InitRequest")
	proto.RegisterType((*Reply)(nil), "simulator.Reply")
	proto.RegisterType((*Proposal)(nil), "simulator.Proposal")
	proto.RegisterType((*Empty)(nil), "simulator.Empty")
}

func init() { proto.RegisterFile("simulator.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x8d, 0x6e, 0xdd, 0xed, 0x2c, 0xb2, 0x32, 0x8a, 0x94, 0x9e, 0x4a, 0x4f, 0xf5, 0xb2,
	0x2c, 0x7a, 0xf0, 0x0b, 0xe8, 0x61, 0x0f, 0x42, 0x89, 0x7e, 0x81, 0x08, 0x63, 0x09, 0xa4, 0x49,
	0x4c, 0xd2, 0x85, 0x7c, 0x7b, 0xd9, 0xae, 0x5d, 0xa3, 0x57, 0xf1, 0xf8, 0x7e, 0xf9, 0xf3, 0x66,
	0xde, 0x83, 0x95, 0x97, 0xfd, 0xa0, 0x44, 0x30, 0x6e, 0x6d, 0x9d, 0x09, 0x06, 0xf3, 0x23, 0xa8,
	0x09, 0xe6, 0x9c, 0x3e, 0x06, 0xf2, 0x01, 0x4b, 0x58, 0x58, 0x25, 0x22, 0xb9, 0xed, 0x63, 0xc1,
	0x2a, 0xd6, 0x64, 0xfc, 0xa8, 0xb1, 0x81, 0x95, 0xd4, 0x81, 0x9c, 0x16, 0xea, 0xd9, 0x77, 0xaf,
	0xd1, 0x52, 0x71, 0x5a, 0xb1, 0xe6, 0x82, 0xff, 0xc6, 0x78, 0x0d, 0xd9, 0x4e, 0xa8, 0x81, 0x8a,
	0xb3, 0x8a, 0x35, 0x39, 0x3f, 0x88, 0xfa, 0x16, 0x96, 0x5b, 0x2d, 0x43, 0x62, 0xa5, 0xdb, 0xf1,
	0x6f, 0x3f, 0x59, 0x4d, 0xba, 0x96, 0x90, 0x71, 0xb2, 0x2a, 0x62, 0x05, 0xcb, 0x9e, 0xbc, 0x17,
	0x1d, 0x8d, 0x7e, 0x87, 0x7b, 0x29, 0xfa, 0xf3, 0x54, 0xef, 0xb0, 0x68, 0x9d, 0xb1, 0xc6, 0x0b,
	0xf5, 0xaf, 0xdb, 0xcf, 0x21, 0x7b, 0xea, 0x6d, 0x88, 0x77, 0x3b, 0xc8, 0x5f, 0xa6, 0xe8, 0x71,
	0x03, 0xb3, 0x56, 0xea, 0x0e, 0x71, 0xfd, 0xdd, 0xcf, 0x57, 0x40, 0xe5, 0xe5, 0x0f, 0x66, 0x55,
	0xac, 0x4f, 0x36, 0x0c, 0x1f, 0x60, 0xb6, 0x4f, 0x11, 0x6f, 0x92, 0xd3, 0x24, 0xd6, 0xf2, 0x2a,
	0xe1, 0xd3, 0x62, 0xfb, 0x87, 0x6f, 0xe7, 0x63, 0xef, 0xf7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x76, 0x5c, 0xd5, 0xb7, 0x0a, 0x02, 0x00, 0x00,
}
