// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blockchain.proto

package iproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConsensusPb_ConsensusMessageType int32

const (
	ConsensusPb_PROPOSAL    ConsensusPb_ConsensusMessageType = 0
	ConsensusPb_ENDORSEMENT ConsensusPb_ConsensusMessageType = 1
)

var ConsensusPb_ConsensusMessageType_name = map[int32]string{
	0: "PROPOSAL",
	1: "ENDORSEMENT",
}
var ConsensusPb_ConsensusMessageType_value = map[string]int32{
	"PROPOSAL":    0,
	"ENDORSEMENT": 1,
}

func (x ConsensusPb_ConsensusMessageType) String() string {
	return proto.EnumName(ConsensusPb_ConsensusMessageType_name, int32(x))
}
func (ConsensusPb_ConsensusMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_b1769ccaa201bbf2, []int{6, 0}
}

type EndorsePb_ConsensusVoteTopic int32

const (
	EndorsePb_PROPOSAL EndorsePb_ConsensusVoteTopic = 0
	EndorsePb_LOCK     EndorsePb_ConsensusVoteTopic = 1
	EndorsePb_COMMIT   EndorsePb_ConsensusVoteTopic = 2
)

var EndorsePb_ConsensusVoteTopic_name = map[int32]string{
	0: "PROPOSAL",
	1: "LOCK",
	2: "COMMIT",
}
var EndorsePb_ConsensusVoteTopic_value = map[string]int32{
	"PROPOSAL": 0,
	"LOCK":     1,
	"COMMIT":   2,
}

func (x EndorsePb_ConsensusVoteTopic) String() string {
	return proto.EnumName(EndorsePb_ConsensusVoteTopic_name, int32(x))
}
func (EndorsePb_ConsensusVoteTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_b1769ccaa201bbf2, []int{8, 0}
}

// header of a block
type BlockHeaderPb struct {
	Version              uint32               `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ChainID              uint32               `protobuf:"varint,2,opt,name=chainID,proto3" json:"chainID,omitempty"`
	Height               uint64               `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PrevBlockHash        []byte               `protobuf:"bytes,5,opt,name=prevBlockHash,proto3" json:"prevBlockHash,omitempty"`
	TxRoot               []byte               `protobuf:"bytes,6,opt,name=txRoot,proto3" json:"txRoot,omitempty"`
	StateRoot            []byte               `protobuf:"bytes,7,opt,name=stateRoot,proto3" json:"stateRoot,omitempty"`
	ReceiptRoot          []byte               `protobuf:"bytes,8,opt,name=receiptRoot,proto3" json:"receiptRoot,omitempty"`
	Reserved             []byte               `protobuf:"bytes,9,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Signature            []byte               `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	Pubkey               []byte               `protobuf:"bytes,11,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	DkgID                []byte               `protobuf:"bytes,12,opt,name=dkgID,proto3" json:"dkgID,omitempty"`
	DkgPubkey            []byte               `protobuf:"bytes,13,opt,name=dkgPubkey,proto3" json:"dkgPubkey,omitempty"`
	DkgSignature         []byte               `protobuf:"bytes,14,opt,name=dkgSignature,proto3" json:"dkgSignature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BlockHeaderPb) Reset()         { *m = BlockHeaderPb{} }
func (m *BlockHeaderPb) String() string { return proto.CompactTextString(m) }
func (*BlockHeaderPb) ProtoMessage()    {}
func (*BlockHeaderPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_b1769ccaa201bbf2, []int{0}
}
func (m *BlockHeaderPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeaderPb.Unmarshal(m, b)
}
func (m *BlockHeaderPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeaderPb.Marshal(b, m, deterministic)
}
func (dst *BlockHeaderPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeaderPb.Merge(dst, src)
}
func (m *BlockHeaderPb) XXX_Size() int {
	return xxx_messageInfo_BlockHeaderPb.Size(m)
}
func (m *BlockHeaderPb) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeaderPb.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeaderPb proto.InternalMessageInfo

func (m *BlockHeaderPb) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BlockHeaderPb) GetChainID() uint32 {
	if m != nil {
		return m.ChainID
	}
	return 0
}

func (m *BlockHeaderPb) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockHeaderPb) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *BlockHeaderPb) GetPrevBlockHash() []byte {
	if m != nil {
		return m.PrevBlockHash
	}
	return nil
}

func (m *BlockHeaderPb) GetTxRoot() []byte {
	if m != nil {
		return m.TxRoot
	}
	return nil
}

func (m *BlockHeaderPb) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *BlockHeaderPb) GetReceiptRoot() []byte {
	if m != nil {
		return m.ReceiptRoot
	}
	return nil
}

func (m *BlockHeaderPb) GetReserved() []byte {
	if m != nil {
		return m.Reserved
	}
	return nil
}

func (m *BlockHeaderPb) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *BlockHeaderPb) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *BlockHeaderPb) GetDkgID() []byte {
	if m != nil {
		return m.DkgID
	}
	return nil
}

func (m *BlockHeaderPb) GetDkgPubkey() []byte {
	if m != nil {
		return m.DkgPubkey
	}
	return nil
}

func (m *BlockHeaderPb) GetDkgSignature() []byte {
	if m != nil {
		return m.DkgSignature
	}
	return nil
}

// block consists of header followed by transactions
// hash of current block can be computed from header hence not stored
type BlockPb struct {
	Header               *BlockHeaderPb `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Actions              []*ActionPb    `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockPb) Reset()         { *m = BlockPb{} }
func (m *BlockPb) String() string { return proto.CompactTextString(m) }
func (*BlockPb) ProtoMessage()    {}
func (*BlockPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_b1769ccaa201bbf2, []int{1}
}
func (m *BlockPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockPb.Unmarshal(m, b)
}
func (m *BlockPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockPb.Marshal(b, m, deterministic)
}
func (dst *BlockPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockPb.Merge(dst, src)
}
func (m *BlockPb) XXX_Size() int {
	return xxx_messageInfo_BlockPb.Size(m)
}
func (m *BlockPb) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockPb.DiscardUnknown(m)
}

var xxx_messageInfo_BlockPb proto.InternalMessageInfo

func (m *BlockPb) GetHeader() *BlockHeaderPb {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BlockPb) GetActions() []*ActionPb {
	if m != nil {
		return m.Actions
	}
	return nil
}

// Receipts consists of a collection of recepit
type Receipts struct {
	Receipts             []*ReceiptPb `protobuf:"bytes,1,rep,name=receipts,proto3" json:"receipts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Receipts) Reset()         { *m = Receipts{} }
func (m *Receipts) String() string { return proto.CompactTextString(m) }
func (*Receipts) ProtoMessage()    {}
func (*Receipts) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_b1769ccaa201bbf2, []int{2}
}
func (m *Receipts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipts.Unmarshal(m, b)
}
func (m *Receipts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipts.Marshal(b, m, deterministic)
}
func (dst *Receipts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipts.Merge(dst, src)
}
func (m *Receipts) XXX_Size() int {
	return xxx_messageInfo_Receipts.Size(m)
}
func (m *Receipts) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipts.DiscardUnknown(m)
}

var xxx_messageInfo_Receipts proto.InternalMessageInfo

func (m *Receipts) GetReceipts() []*ReceiptPb {
	if m != nil {
		return m.Receipts
	}
	return nil
}

// index of block raw data file
type BlockIndex struct {
	Start                uint64   `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  uint64   `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Offset               []uint32 `protobuf:"varint,3,rep,packed,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockIndex) Reset()         { *m = BlockIndex{} }
func (m *BlockIndex) String() string { return proto.CompactTextString(m) }
func (*BlockIndex) ProtoMessage()    {}
func (*BlockIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_b1769ccaa201bbf2, []int{3}
}
func (m *BlockIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockIndex.Unmarshal(m, b)
}
func (m *BlockIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockIndex.Marshal(b, m, deterministic)
}
func (dst *BlockIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockIndex.Merge(dst, src)
}
func (m *BlockIndex) XXX_Size() int {
	return xxx_messageInfo_BlockIndex.Size(m)
}
func (m *BlockIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockIndex.DiscardUnknown(m)
}

var xxx_messageInfo_BlockIndex proto.InternalMessageInfo

func (m *BlockIndex) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *BlockIndex) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *BlockIndex) GetOffset() []uint32 {
	if m != nil {
		return m.Offset
	}
	return nil
}

type BlockSync struct {
	Start                uint64   `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  uint64   `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockSync) Reset()         { *m = BlockSync{} }
func (m *BlockSync) String() string { return proto.CompactTextString(m) }
func (*BlockSync) ProtoMessage()    {}
func (*BlockSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_b1769ccaa201bbf2, []int{4}
}
func (m *BlockSync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockSync.Unmarshal(m, b)
}
func (m *BlockSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockSync.Marshal(b, m, deterministic)
}
func (dst *BlockSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockSync.Merge(dst, src)
}
func (m *BlockSync) XXX_Size() int {
	return xxx_messageInfo_BlockSync.Size(m)
}
func (m *BlockSync) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockSync.DiscardUnknown(m)
}

var xxx_messageInfo_BlockSync proto.InternalMessageInfo

func (m *BlockSync) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *BlockSync) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

// block container
// used to send old/existing blocks in block sync
type BlockContainer struct {
	Block                *BlockPb `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockContainer) Reset()         { *m = BlockContainer{} }
func (m *BlockContainer) String() string { return proto.CompactTextString(m) }
func (*BlockContainer) ProtoMessage()    {}
func (*BlockContainer) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_b1769ccaa201bbf2, []int{5}
}
func (m *BlockContainer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockContainer.Unmarshal(m, b)
}
func (m *BlockContainer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockContainer.Marshal(b, m, deterministic)
}
func (dst *BlockContainer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockContainer.Merge(dst, src)
}
func (m *BlockContainer) XXX_Size() int {
	return xxx_messageInfo_BlockContainer.Size(m)
}
func (m *BlockContainer) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockContainer.DiscardUnknown(m)
}

var xxx_messageInfo_BlockContainer proto.InternalMessageInfo

func (m *BlockContainer) GetBlock() *BlockPb {
	if m != nil {
		return m.Block
	}
	return nil
}

type ConsensusPb struct {
	Height               uint64                           `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                uint32                           `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Type                 ConsensusPb_ConsensusMessageType `protobuf:"varint,3,opt,name=type,proto3,enum=iproto.ConsensusPb_ConsensusMessageType" json:"type,omitempty"`
	Timestamp            *timestamp.Timestamp             `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data                 []byte                           `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ConsensusPb) Reset()         { *m = ConsensusPb{} }
func (m *ConsensusPb) String() string { return proto.CompactTextString(m) }
func (*ConsensusPb) ProtoMessage()    {}
func (*ConsensusPb) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_b1769ccaa201bbf2, []int{6}
}
func (m *ConsensusPb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusPb.Unmarshal(m, b)
}
func (m *ConsensusPb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusPb.Marshal(b, m, deterministic)
}
func (dst *ConsensusPb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusPb.Merge(dst, src)
}
func (m *ConsensusPb) XXX_Size() int {
	return xxx_messageInfo_ConsensusPb.Size(m)
}
func (m *ConsensusPb) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusPb.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusPb proto.InternalMessageInfo

func (m *ConsensusPb) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ConsensusPb) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *ConsensusPb) GetType() ConsensusPb_ConsensusMessageType {
	if m != nil {
		return m.Type
	}
	return ConsensusPb_PROPOSAL
}

func (m *ConsensusPb) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ConsensusPb) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// corresponding to pre-prepare pharse in view change protocol
type ProposePb struct {
	Proposer             string          `protobuf:"bytes,1,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Height               uint64          `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Round                uint32          `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Hash                 []byte          `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Block                []byte          `protobuf:"bytes,5,opt,name=block,proto3" json:"block,omitempty"`
	LockProof            *EndorsementSet `protobuf:"bytes,6,opt,name=lockProof,proto3" json:"lockProof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProposePb) Reset()         { *m = ProposePb{} }
func (m *ProposePb) String() string { return proto.CompactTextString(m) }
func (*ProposePb) ProtoMessage()    {}
func (*ProposePb) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_b1769ccaa201bbf2, []int{7}
}
func (m *ProposePb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposePb.Unmarshal(m, b)
}
func (m *ProposePb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposePb.Marshal(b, m, deterministic)
}
func (dst *ProposePb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposePb.Merge(dst, src)
}
func (m *ProposePb) XXX_Size() int {
	return xxx_messageInfo_ProposePb.Size(m)
}
func (m *ProposePb) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposePb.DiscardUnknown(m)
}

var xxx_messageInfo_ProposePb proto.InternalMessageInfo

func (m *ProposePb) GetProposer() string {
	if m != nil {
		return m.Proposer
	}
	return ""
}

func (m *ProposePb) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ProposePb) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *ProposePb) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ProposePb) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *ProposePb) GetLockProof() *EndorsementSet {
	if m != nil {
		return m.LockProof
	}
	return nil
}

// corresponding to prepare and pre-prepare phase in view change protocol
type EndorsePb struct {
	Height               uint64                       `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                uint32                       `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	BlockHash            []byte                       `protobuf:"bytes,3,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	Topic                EndorsePb_ConsensusVoteTopic `protobuf:"varint,4,opt,name=topic,proto3,enum=iproto.EndorsePb_ConsensusVoteTopic" json:"topic,omitempty"`
	Endorser             string                       `protobuf:"bytes,5,opt,name=endorser,proto3" json:"endorser,omitempty"`
	EndorserPubKey       []byte                       `protobuf:"bytes,6,opt,name=endorserPubKey,proto3" json:"endorserPubKey,omitempty"`
	Decision             bool                         `protobuf:"varint,7,opt,name=decision,proto3" json:"decision,omitempty"`
	Signature            []byte                       `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *EndorsePb) Reset()         { *m = EndorsePb{} }
func (m *EndorsePb) String() string { return proto.CompactTextString(m) }
func (*EndorsePb) ProtoMessage()    {}
func (*EndorsePb) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_b1769ccaa201bbf2, []int{8}
}
func (m *EndorsePb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndorsePb.Unmarshal(m, b)
}
func (m *EndorsePb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndorsePb.Marshal(b, m, deterministic)
}
func (dst *EndorsePb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndorsePb.Merge(dst, src)
}
func (m *EndorsePb) XXX_Size() int {
	return xxx_messageInfo_EndorsePb.Size(m)
}
func (m *EndorsePb) XXX_DiscardUnknown() {
	xxx_messageInfo_EndorsePb.DiscardUnknown(m)
}

var xxx_messageInfo_EndorsePb proto.InternalMessageInfo

func (m *EndorsePb) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *EndorsePb) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *EndorsePb) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *EndorsePb) GetTopic() EndorsePb_ConsensusVoteTopic {
	if m != nil {
		return m.Topic
	}
	return EndorsePb_PROPOSAL
}

func (m *EndorsePb) GetEndorser() string {
	if m != nil {
		return m.Endorser
	}
	return ""
}

func (m *EndorsePb) GetEndorserPubKey() []byte {
	if m != nil {
		return m.EndorserPubKey
	}
	return nil
}

func (m *EndorsePb) GetDecision() bool {
	if m != nil {
		return m.Decision
	}
	return false
}

func (m *EndorsePb) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type EndorsementSet struct {
	BlockHash            []byte       `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	Round                uint32       `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Endorsements         []*EndorsePb `protobuf:"bytes,3,rep,name=endorsements,proto3" json:"endorsements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EndorsementSet) Reset()         { *m = EndorsementSet{} }
func (m *EndorsementSet) String() string { return proto.CompactTextString(m) }
func (*EndorsementSet) ProtoMessage()    {}
func (*EndorsementSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_b1769ccaa201bbf2, []int{9}
}
func (m *EndorsementSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndorsementSet.Unmarshal(m, b)
}
func (m *EndorsementSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndorsementSet.Marshal(b, m, deterministic)
}
func (dst *EndorsementSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndorsementSet.Merge(dst, src)
}
func (m *EndorsementSet) XXX_Size() int {
	return xxx_messageInfo_EndorsementSet.Size(m)
}
func (m *EndorsementSet) XXX_DiscardUnknown() {
	xxx_messageInfo_EndorsementSet.DiscardUnknown(m)
}

var xxx_messageInfo_EndorsementSet proto.InternalMessageInfo

func (m *EndorsementSet) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *EndorsementSet) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *EndorsementSet) GetEndorsements() []*EndorsePb {
	if m != nil {
		return m.Endorsements
	}
	return nil
}

// Candidates and list of candidates
type Candidate struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Votes                []byte   `protobuf:"bytes,2,opt,name=votes,proto3" json:"votes,omitempty"`
	PubKey               []byte   `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	CreationHeight       uint64   `protobuf:"varint,4,opt,name=creationHeight,proto3" json:"creationHeight,omitempty"`
	LastUpdateHeight     uint64   `protobuf:"varint,5,opt,name=lastUpdateHeight,proto3" json:"lastUpdateHeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candidate) Reset()         { *m = Candidate{} }
func (m *Candidate) String() string { return proto.CompactTextString(m) }
func (*Candidate) ProtoMessage()    {}
func (*Candidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_b1769ccaa201bbf2, []int{10}
}
func (m *Candidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidate.Unmarshal(m, b)
}
func (m *Candidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidate.Marshal(b, m, deterministic)
}
func (dst *Candidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidate.Merge(dst, src)
}
func (m *Candidate) XXX_Size() int {
	return xxx_messageInfo_Candidate.Size(m)
}
func (m *Candidate) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidate.DiscardUnknown(m)
}

var xxx_messageInfo_Candidate proto.InternalMessageInfo

func (m *Candidate) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Candidate) GetVotes() []byte {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *Candidate) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Candidate) GetCreationHeight() uint64 {
	if m != nil {
		return m.CreationHeight
	}
	return 0
}

func (m *Candidate) GetLastUpdateHeight() uint64 {
	if m != nil {
		return m.LastUpdateHeight
	}
	return 0
}

type CandidateList struct {
	Candidates           []*Candidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CandidateList) Reset()         { *m = CandidateList{} }
func (m *CandidateList) String() string { return proto.CompactTextString(m) }
func (*CandidateList) ProtoMessage()    {}
func (*CandidateList) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_b1769ccaa201bbf2, []int{11}
}
func (m *CandidateList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateList.Unmarshal(m, b)
}
func (m *CandidateList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateList.Marshal(b, m, deterministic)
}
func (dst *CandidateList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateList.Merge(dst, src)
}
func (m *CandidateList) XXX_Size() int {
	return xxx_messageInfo_CandidateList.Size(m)
}
func (m *CandidateList) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateList.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateList proto.InternalMessageInfo

func (m *CandidateList) GetCandidates() []*Candidate {
	if m != nil {
		return m.Candidates
	}
	return nil
}

// //////////////////////////////////////////////////////////////////////////////////////////////////
// BELOW ARE DEFINITIONS FOR TEST-ONLY MESSAGES!
// //////////////////////////////////////////////////////////////////////////////////////////////////
type TestPayload struct {
	MsgBody              []byte   `protobuf:"bytes,1,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestPayload) Reset()         { *m = TestPayload{} }
func (m *TestPayload) String() string { return proto.CompactTextString(m) }
func (*TestPayload) ProtoMessage()    {}
func (*TestPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_b1769ccaa201bbf2, []int{12}
}
func (m *TestPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestPayload.Unmarshal(m, b)
}
func (m *TestPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestPayload.Marshal(b, m, deterministic)
}
func (dst *TestPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestPayload.Merge(dst, src)
}
func (m *TestPayload) XXX_Size() int {
	return xxx_messageInfo_TestPayload.Size(m)
}
func (m *TestPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_TestPayload.DiscardUnknown(m)
}

var xxx_messageInfo_TestPayload proto.InternalMessageInfo

func (m *TestPayload) GetMsgBody() []byte {
	if m != nil {
		return m.MsgBody
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockHeaderPb)(nil), "iproto.BlockHeaderPb")
	proto.RegisterType((*BlockPb)(nil), "iproto.BlockPb")
	proto.RegisterType((*Receipts)(nil), "iproto.Receipts")
	proto.RegisterType((*BlockIndex)(nil), "iproto.BlockIndex")
	proto.RegisterType((*BlockSync)(nil), "iproto.BlockSync")
	proto.RegisterType((*BlockContainer)(nil), "iproto.BlockContainer")
	proto.RegisterType((*ConsensusPb)(nil), "iproto.ConsensusPb")
	proto.RegisterType((*ProposePb)(nil), "iproto.ProposePb")
	proto.RegisterType((*EndorsePb)(nil), "iproto.EndorsePb")
	proto.RegisterType((*EndorsementSet)(nil), "iproto.EndorsementSet")
	proto.RegisterType((*Candidate)(nil), "iproto.Candidate")
	proto.RegisterType((*CandidateList)(nil), "iproto.CandidateList")
	proto.RegisterType((*TestPayload)(nil), "iproto.TestPayload")
	proto.RegisterEnum("iproto.ConsensusPb_ConsensusMessageType", ConsensusPb_ConsensusMessageType_name, ConsensusPb_ConsensusMessageType_value)
	proto.RegisterEnum("iproto.EndorsePb_ConsensusVoteTopic", EndorsePb_ConsensusVoteTopic_name, EndorsePb_ConsensusVoteTopic_value)
}

func init() { proto.RegisterFile("blockchain.proto", fileDescriptor_blockchain_b1769ccaa201bbf2) }

var fileDescriptor_blockchain_b1769ccaa201bbf2 = []byte{
	// 929 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x2e, 0x25, 0xca, 0x12, 0x47, 0x3f, 0x51, 0x17, 0x6e, 0xc0, 0x1a, 0x01, 0x2a, 0x10, 0x69,
	0x20, 0x04, 0x88, 0x82, 0x2a, 0x0d, 0x9a, 0x16, 0xbd, 0xc4, 0xb2, 0x81, 0x18, 0xb1, 0x23, 0x62,
	0xa5, 0xf6, 0x5a, 0x2c, 0xb5, 0x63, 0x8a, 0x90, 0xc5, 0x25, 0xb8, 0x2b, 0x23, 0x42, 0x1f, 0xa8,
	0x4f, 0xd0, 0x63, 0x9f, 0xa0, 0xef, 0x54, 0x14, 0xbb, 0x4b, 0x52, 0x3f, 0xf6, 0xa5, 0xe8, 0x49,
	0xfb, 0xcd, 0x7c, 0x3b, 0x33, 0xfc, 0x76, 0x66, 0x04, 0xfd, 0xe8, 0x4e, 0x2c, 0x56, 0x8b, 0x25,
	0x4b, 0xd2, 0x51, 0x96, 0x0b, 0x25, 0xc8, 0x49, 0x62, 0x7e, 0xcf, 0x3a, 0x6c, 0xa1, 0x12, 0x51,
	0x58, 0xcf, 0xbe, 0x89, 0x85, 0x88, 0xef, 0xf0, 0xb5, 0x41, 0xd1, 0xe6, 0xf6, 0xb5, 0x4a, 0xd6,
	0x28, 0x15, 0x5b, 0x67, 0x96, 0x10, 0xfc, 0x55, 0x87, 0xee, 0xb9, 0x8e, 0xf5, 0x01, 0x19, 0xc7,
	0x3c, 0x8c, 0x88, 0x0f, 0xcd, 0x7b, 0xcc, 0x65, 0x22, 0x52, 0xdf, 0x19, 0x38, 0xc3, 0x2e, 0x2d,
	0xa1, 0xf6, 0x98, 0x8c, 0x57, 0x17, 0x7e, 0xcd, 0x7a, 0x0a, 0x48, 0x9e, 0xc2, 0xc9, 0x12, 0x93,
	0x78, 0xa9, 0xfc, 0xfa, 0xc0, 0x19, 0xba, 0xb4, 0x40, 0xe4, 0x1d, 0x78, 0x55, 0x42, 0xdf, 0x1d,
	0x38, 0xc3, 0xf6, 0xf8, 0x6c, 0x64, 0x4b, 0x1a, 0x95, 0x25, 0x8d, 0xe6, 0x25, 0x83, 0xee, 0xc8,
	0xe4, 0x39, 0x74, 0xb3, 0x1c, 0xef, 0x6d, 0x69, 0x4c, 0x2e, 0xfd, 0xc6, 0xc0, 0x19, 0x76, 0xe8,
	0xa1, 0x51, 0xe7, 0x55, 0x9f, 0xa9, 0x10, 0xca, 0x3f, 0x31, 0xee, 0x02, 0x91, 0x67, 0xe0, 0x49,
	0xc5, 0x14, 0x1a, 0x57, 0xd3, 0xb8, 0x76, 0x06, 0x32, 0x80, 0x76, 0x8e, 0x0b, 0x4c, 0x32, 0x65,
	0xfc, 0x2d, 0xe3, 0xdf, 0x37, 0x91, 0x33, 0x68, 0xe5, 0x28, 0x31, 0xbf, 0x47, 0xee, 0x7b, 0xc6,
	0x5d, 0x61, 0x13, 0x3b, 0x89, 0x53, 0xa6, 0x36, 0x39, 0xfa, 0x50, 0xc4, 0x2e, 0x0d, 0xba, 0xa2,
	0x6c, 0x13, 0xad, 0x70, 0xeb, 0xb7, 0x6d, 0x45, 0x16, 0x91, 0x53, 0x68, 0xf0, 0x55, 0x7c, 0x75,
	0xe1, 0x77, 0x8c, 0xd9, 0x02, 0x1d, 0x8b, 0xaf, 0xe2, 0xd0, 0x5e, 0xe8, 0xda, 0x58, 0x95, 0x81,
	0x04, 0xd0, 0xe1, 0xab, 0x78, 0x56, 0x25, 0xeb, 0x19, 0xc2, 0x81, 0x2d, 0xe0, 0xd0, 0x34, 0x72,
	0x84, 0x11, 0x79, 0xa5, 0x1f, 0x41, 0x3f, 0xa2, 0x79, 0xb7, 0xf6, 0xf8, 0xab, 0x91, 0x6d, 0x89,
	0xd1, 0xc1, 0xfb, 0xd2, 0x82, 0x44, 0x5e, 0x42, 0xd3, 0xb6, 0x8a, 0xf4, 0x6b, 0x83, 0xfa, 0xb0,
	0x3d, 0xee, 0x97, 0xfc, 0xf7, 0xc6, 0x1c, 0x46, 0xb4, 0x24, 0x04, 0x3f, 0x42, 0x8b, 0x5a, 0x79,
	0x24, 0x79, 0xa5, 0xb5, 0xb1, 0x67, 0xdf, 0x31, 0x17, 0xbf, 0x2c, 0x2f, 0x16, 0x9c, 0x30, 0xa2,
	0x15, 0x25, 0xb8, 0x06, 0x30, 0xf9, 0xaf, 0x52, 0x8e, 0x9f, 0xb5, 0x0c, 0x52, 0xb1, 0x5c, 0x99,
	0x12, 0x5d, 0x6a, 0x01, 0xe9, 0x43, 0x1d, 0x53, 0x6e, 0x9a, 0xca, 0xa5, 0xfa, 0xa8, 0x65, 0x14,
	0xb7, 0xb7, 0x12, 0x75, 0x43, 0xd5, 0x87, 0x5d, 0x5a, 0xa0, 0xe0, 0x0d, 0x78, 0x26, 0xda, 0x6c,
	0x9b, 0x2e, 0x76, 0xc1, 0x6a, 0x8f, 0x04, 0xab, 0x57, 0xc1, 0x82, 0x1f, 0xa0, 0x67, 0x2e, 0x4d,
	0x44, 0xaa, 0x58, 0x92, 0x62, 0x4e, 0xbe, 0x85, 0x86, 0x19, 0xa0, 0x42, 0xa9, 0x27, 0x07, 0x4a,
	0x85, 0x11, 0xb5, 0xde, 0xe0, 0x1f, 0x07, 0xda, 0x13, 0x91, 0x4a, 0x4c, 0xe5, 0x46, 0x86, 0xd1,
	0x5e, 0x9b, 0x3b, 0x07, 0x6d, 0x7e, 0x0a, 0x8d, 0x5c, 0x6c, 0x8a, 0x2f, 0xe8, 0x52, 0x0b, 0xc8,
	0xcf, 0xe0, 0xaa, 0x6d, 0x86, 0xa6, 0x92, 0xde, 0x78, 0x58, 0xe6, 0xd8, 0x0b, 0xb8, 0x3b, 0xdf,
	0xa0, 0x94, 0x2c, 0xc6, 0xf9, 0x36, 0x43, 0x6a, 0x6e, 0xfd, 0x8f, 0xd1, 0x21, 0xe0, 0x72, 0xa6,
	0x58, 0x31, 0x31, 0xe6, 0x1c, 0xbc, 0x85, 0xd3, 0xc7, 0x72, 0x91, 0x0e, 0xb4, 0x42, 0x3a, 0x0d,
	0xa7, 0xb3, 0xf7, 0xd7, 0xfd, 0x2f, 0xc8, 0x13, 0x68, 0x5f, 0x7e, 0xba, 0x98, 0xd2, 0xd9, 0xe5,
	0xcd, 0xe5, 0xa7, 0x79, 0xdf, 0x09, 0xfe, 0x74, 0xc0, 0x0b, 0x73, 0x91, 0x09, 0x89, 0x61, 0xa4,
	0xa7, 0x22, 0xb3, 0xc0, 0xb6, 0x98, 0x47, 0x2b, 0xbc, 0x27, 0x4d, 0xed, 0x71, 0x69, 0xea, 0xfb,
	0xd2, 0x10, 0x70, 0x97, 0x7a, 0xa8, 0x5d, 0x5b, 0xa2, 0x3e, 0x6b, 0xa6, 0x7d, 0x13, 0x5b, 0xb7,
	0x05, 0xe4, 0x7b, 0xf0, 0xcc, 0x9b, 0xe4, 0x42, 0xdc, 0x9a, 0x21, 0x6f, 0x8f, 0x9f, 0x96, 0x4a,
	0x5e, 0xa6, 0x5c, 0xe4, 0x12, 0xd7, 0x98, 0xaa, 0x19, 0x2a, 0xba, 0x23, 0x06, 0x7f, 0xd7, 0xc0,
	0x2b, 0xbc, 0xff, 0xf9, 0xd9, 0x9e, 0x81, 0x17, 0x55, 0x5b, 0xa7, 0x6e, 0x67, 0xb2, 0x32, 0x90,
	0x9f, 0xa0, 0xa1, 0x44, 0x96, 0x2c, 0x4c, 0xe9, 0xbd, 0xf1, 0xf3, 0xa3, 0x5a, 0xf6, 0xdf, 0xf4,
	0x57, 0xa1, 0x70, 0xae, 0xb9, 0xd4, 0x5e, 0xd1, 0xfa, 0xa1, 0xa5, 0xe5, 0xe6, 0x23, 0x3d, 0x5a,
	0x61, 0xf2, 0x02, 0x7a, 0xe5, 0x39, 0xdc, 0x44, 0x1f, 0x71, 0x5b, 0x6c, 0xb4, 0x23, 0xab, 0x8e,
	0xc1, 0x71, 0x91, 0x98, 0xf5, 0xac, 0x17, 0x5b, 0x8b, 0x56, 0xf8, 0x70, 0x33, 0xb5, 0x8e, 0x36,
	0x53, 0xf0, 0x0e, 0xc8, 0xc3, 0xd2, 0x8e, 0x1a, 0xa0, 0x05, 0xee, 0xf5, 0x74, 0xf2, 0xb1, 0xef,
	0x10, 0x80, 0x93, 0xc9, 0xf4, 0xe6, 0xe6, 0x6a, 0xde, 0xaf, 0x05, 0xbf, 0x43, 0xef, 0x50, 0xea,
	0x43, 0x8d, 0x9c, 0x63, 0x8d, 0x1e, 0xd7, 0xf5, 0x2d, 0x74, 0x70, 0x17, 0x45, 0x9a, 0xc1, 0xde,
	0xdb, 0x1d, 0x95, 0x80, 0xf4, 0x80, 0x16, 0xfc, 0xe1, 0x80, 0x37, 0x61, 0x29, 0x4f, 0x38, 0x53,
	0xa8, 0xff, 0x82, 0x18, 0xe7, 0x39, 0x4a, 0x59, 0x74, 0x60, 0x09, 0x75, 0xd2, 0x7b, 0xa1, 0x50,
	0x9a, 0xa4, 0x1d, 0x6a, 0x41, 0xb1, 0x8e, 0xb5, 0x9c, 0xf5, 0x6a, 0x1d, 0x6b, 0x19, 0x5f, 0x40,
	0x6f, 0x91, 0x23, 0xd3, 0xdb, 0xed, 0x83, 0x6d, 0x0d, 0xd7, 0xb4, 0xc6, 0x91, 0x95, 0xbc, 0x84,
	0xfe, 0x1d, 0x93, 0xea, 0x97, 0x4c, 0x67, 0x2f, 0x98, 0x0d, 0xc3, 0x7c, 0x60, 0x0f, 0xce, 0xa1,
	0x5b, 0x15, 0x7a, 0x9d, 0x48, 0x45, 0xbe, 0x03, 0x58, 0x94, 0x86, 0x07, 0xbb, 0xb2, 0xa2, 0xd2,
	0x3d, 0x52, 0x30, 0x84, 0xf6, 0x1c, 0xa5, 0x0a, 0xd9, 0xf6, 0x4e, 0x30, 0x4e, 0xbe, 0x86, 0xd6,
	0x5a, 0xc6, 0xbf, 0x45, 0x82, 0x6f, 0x0b, 0x99, 0x9b, 0x6b, 0x19, 0x9f, 0x0b, 0xbe, 0x8d, 0x4e,
	0x4c, 0x98, 0x37, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x08, 0x0b, 0x6a, 0x2e, 0x0a, 0x08, 0x00,
	0x00,
}
