// Code generated by protoc-gen-go. DO NOT EDIT.
// source: endorsement.proto

package iproto // import "github.com/iotexproject/iotex-core/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Endorsement_ConsensusVoteTopic int32

const (
	Endorsement_PROPOSAL Endorsement_ConsensusVoteTopic = 0
	Endorsement_LOCK     Endorsement_ConsensusVoteTopic = 1
	Endorsement_COMMIT   Endorsement_ConsensusVoteTopic = 2
)

var Endorsement_ConsensusVoteTopic_name = map[int32]string{
	0: "PROPOSAL",
	1: "LOCK",
	2: "COMMIT",
}
var Endorsement_ConsensusVoteTopic_value = map[string]int32{
	"PROPOSAL": 0,
	"LOCK":     1,
	"COMMIT":   2,
}

func (x Endorsement_ConsensusVoteTopic) String() string {
	return proto.EnumName(Endorsement_ConsensusVoteTopic_name, int32(x))
}
func (Endorsement_ConsensusVoteTopic) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_endorsement_fdbd9d8a2a859a65, []int{0, 0}
}

// corresponding to prepare and pre-prepare phase in view change protocol
type Endorsement struct {
	Height               uint64                         `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                uint32                         `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	BlockHash            []byte                         `protobuf:"bytes,3,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	Topic                Endorsement_ConsensusVoteTopic `protobuf:"varint,4,opt,name=topic,proto3,enum=iproto.Endorsement_ConsensusVoteTopic" json:"topic,omitempty"`
	Endorser             string                         `protobuf:"bytes,5,opt,name=endorser,proto3" json:"endorser,omitempty"`
	EndorserPubKey       []byte                         `protobuf:"bytes,6,opt,name=endorserPubKey,proto3" json:"endorserPubKey,omitempty"`
	Decision             bool                           `protobuf:"varint,7,opt,name=decision,proto3" json:"decision,omitempty"`
	Signature            []byte                         `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Endorsement) Reset()         { *m = Endorsement{} }
func (m *Endorsement) String() string { return proto.CompactTextString(m) }
func (*Endorsement) ProtoMessage()    {}
func (*Endorsement) Descriptor() ([]byte, []int) {
	return fileDescriptor_endorsement_fdbd9d8a2a859a65, []int{0}
}
func (m *Endorsement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endorsement.Unmarshal(m, b)
}
func (m *Endorsement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endorsement.Marshal(b, m, deterministic)
}
func (dst *Endorsement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endorsement.Merge(dst, src)
}
func (m *Endorsement) XXX_Size() int {
	return xxx_messageInfo_Endorsement.Size(m)
}
func (m *Endorsement) XXX_DiscardUnknown() {
	xxx_messageInfo_Endorsement.DiscardUnknown(m)
}

var xxx_messageInfo_Endorsement proto.InternalMessageInfo

func (m *Endorsement) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Endorsement) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Endorsement) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *Endorsement) GetTopic() Endorsement_ConsensusVoteTopic {
	if m != nil {
		return m.Topic
	}
	return Endorsement_PROPOSAL
}

func (m *Endorsement) GetEndorser() string {
	if m != nil {
		return m.Endorser
	}
	return ""
}

func (m *Endorsement) GetEndorserPubKey() []byte {
	if m != nil {
		return m.EndorserPubKey
	}
	return nil
}

func (m *Endorsement) GetDecision() bool {
	if m != nil {
		return m.Decision
	}
	return false
}

func (m *Endorsement) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type EndorsementSet struct {
	BlockHash            []byte         `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	Round                uint32         `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Endorsements         []*Endorsement `protobuf:"bytes,3,rep,name=endorsements,proto3" json:"endorsements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *EndorsementSet) Reset()         { *m = EndorsementSet{} }
func (m *EndorsementSet) String() string { return proto.CompactTextString(m) }
func (*EndorsementSet) ProtoMessage()    {}
func (*EndorsementSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_endorsement_fdbd9d8a2a859a65, []int{1}
}
func (m *EndorsementSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndorsementSet.Unmarshal(m, b)
}
func (m *EndorsementSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndorsementSet.Marshal(b, m, deterministic)
}
func (dst *EndorsementSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndorsementSet.Merge(dst, src)
}
func (m *EndorsementSet) XXX_Size() int {
	return xxx_messageInfo_EndorsementSet.Size(m)
}
func (m *EndorsementSet) XXX_DiscardUnknown() {
	xxx_messageInfo_EndorsementSet.DiscardUnknown(m)
}

var xxx_messageInfo_EndorsementSet proto.InternalMessageInfo

func (m *EndorsementSet) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *EndorsementSet) GetRound() uint32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *EndorsementSet) GetEndorsements() []*Endorsement {
	if m != nil {
		return m.Endorsements
	}
	return nil
}

func init() {
	proto.RegisterType((*Endorsement)(nil), "iproto.Endorsement")
	proto.RegisterType((*EndorsementSet)(nil), "iproto.EndorsementSet")
	proto.RegisterEnum("iproto.Endorsement_ConsensusVoteTopic", Endorsement_ConsensusVoteTopic_name, Endorsement_ConsensusVoteTopic_value)
}

func init() { proto.RegisterFile("endorsement.proto", fileDescriptor_endorsement_fdbd9d8a2a859a65) }

var fileDescriptor_endorsement_fdbd9d8a2a859a65 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4f, 0x2a, 0x31,
	0x14, 0x7d, 0xe5, 0x63, 0xde, 0x70, 0xe1, 0x11, 0x5e, 0xdf, 0x8b, 0x69, 0x8c, 0x8b, 0x86, 0x05,
	0xe9, 0xc6, 0x21, 0xe2, 0x42, 0x13, 0xdd, 0x28, 0x31, 0xd1, 0x00, 0x19, 0x52, 0x88, 0x0b, 0x77,
	0xcc, 0xd0, 0x30, 0x55, 0x69, 0x49, 0xdb, 0x49, 0x74, 0xe1, 0x6f, 0xf4, 0x2f, 0x19, 0x66, 0x90,
	0x2f, 0x59, 0xdd, 0x39, 0x67, 0x6e, 0xcf, 0x39, 0x3d, 0x85, 0xbf, 0x42, 0x4d, 0xb5, 0xb1, 0x62,
	0x2e, 0x94, 0x0b, 0x16, 0x46, 0x3b, 0x8d, 0x3d, 0x99, 0xcd, 0xe6, 0x67, 0x01, 0xaa, 0x77, 0x9b,
	0xbf, 0xf8, 0x08, 0xbc, 0x44, 0xc8, 0x59, 0xe2, 0x08, 0xa2, 0x88, 0x95, 0xf8, 0x0a, 0xe1, 0xff,
	0x50, 0x36, 0x3a, 0x55, 0x53, 0x52, 0xa0, 0x88, 0xfd, 0xe1, 0x39, 0xc0, 0x27, 0x50, 0x89, 0x5e,
	0x75, 0xfc, 0x72, 0x3f, 0xb1, 0x09, 0x29, 0x52, 0xc4, 0x6a, 0x7c, 0x43, 0xe0, 0x6b, 0x28, 0x3b,
	0xbd, 0x90, 0x31, 0x29, 0x51, 0xc4, 0xea, 0x9d, 0x56, 0x90, 0x7b, 0x06, 0x5b, 0x7e, 0x41, 0x57,
	0x2b, 0x2b, 0x94, 0x4d, 0xed, 0xa3, 0x76, 0x62, 0xbc, 0xdc, 0xe6, 0xf9, 0x21, 0x7c, 0x0c, 0xfe,
	0x2a, 0xb6, 0x21, 0x65, 0x8a, 0x58, 0x85, 0xaf, 0x31, 0x6e, 0x41, 0xfd, 0xfb, 0x7b, 0x98, 0x46,
	0x3d, 0xf1, 0x4e, 0xbc, 0xcc, 0x7c, 0x8f, 0x5d, 0x6a, 0x4c, 0x45, 0x2c, 0xad, 0xd4, 0x8a, 0xfc,
	0xa6, 0x88, 0xf9, 0x7c, 0x8d, 0x97, 0xd9, 0xad, 0x9c, 0xa9, 0x89, 0x4b, 0x8d, 0x20, 0x7e, 0x9e,
	0x7d, 0x4d, 0x34, 0x2f, 0x01, 0xff, 0x8c, 0x86, 0x6b, 0xe0, 0x0f, 0x79, 0x38, 0x0c, 0x47, 0x37,
	0xfd, 0xc6, 0x2f, 0xec, 0x43, 0xa9, 0x1f, 0x76, 0x7b, 0x0d, 0x84, 0x01, 0xbc, 0x6e, 0x38, 0x18,
	0x3c, 0x8c, 0x1b, 0x85, 0xe6, 0x07, 0xd4, 0xb7, 0x2e, 0x38, 0x12, 0x6e, 0xb7, 0x25, 0xb4, 0xdf,
	0xd2, 0xe1, 0x66, 0x2f, 0xa0, 0xb6, 0xf5, 0x68, 0x96, 0x14, 0x69, 0x91, 0x55, 0x3b, 0xff, 0x0e,
	0x54, 0xc8, 0x77, 0x16, 0x6f, 0xcf, 0x9e, 0xda, 0x33, 0xe9, 0x92, 0x34, 0x0a, 0x62, 0x3d, 0x6f,
	0x4b, 0xed, 0xc4, 0xdb, 0xc2, 0xe8, 0x67, 0x11, 0xbb, 0x1c, 0x9c, 0xc6, 0xda, 0x88, 0x76, 0xa6,
	0x72, 0x95, 0x8b, 0x45, 0x5e, 0x36, 0xce, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xfd, 0x0f,
	0x0a, 0x27, 0x02, 0x00, 0x00,
}
