# go-yaml expects the YAML field corresponding to a struct field to be lowercase. So if your struct field is
# UpdateInterval, the corresponding field in YAML is updateinterval.

nodeType: "INIT FROM CODE"       # should be one of "delegate", "full_node", and "lightweight"

network:
    addr: "INIT FROM CODE"
    msgLogsCleaningInterval: 2s
    msgLogRetention: 10s
    healthCheckInterval: 1s
    silentInterval: 5s
    peerMaintainerInterval: 1s
    allowMultiConnsperIP: true
    numPeersLowerBound: 6
    numPeersUpperBound: 12
    pingInterval: 1s
    rateLimitEnabled: false
    rateLimitPerSec: 5
    rateLimitWindowSize: 60s
    bootstrapNodes:
        - "127.0.0.1:40000"
        - "127.0.0.1:40001"
        - "127.0.0.1:40002"
        - "127.0.0.1:40003"
    maxMsgSize: 10485760
    peerDiscovery: true

chain:
    chainDBPath: "../chain.db"
    trieDBPath: "../trie.db"
    rawMinerAddr:
        privateKey: "7fbb20b87d34eade61351165aa4c6fa5d87dd349368dd6b9034ea3d3e918c706b9b8d7316705dc4ff62bb323e610f3f5072abedc9834e999d6537f6681284ea2"
        publicKey: "b9b8d7316705dc4ff62bb323e610f3f5072abedc9834e999d6537f6681284ea2"
        rawAddress: "io1qyqsyqcy6nm58gjd2wr035wz5eyd5uq47zyqpng3gxe7nh"
    inMemTest: false

consensus:
    scheme: "ROLLDPOS"
    rollDPoS:
        proposerInterval: 0ms
        unmatchedEventTTL: 90ms
        acceptPropose:
            ttl: 90ms
        acceptPrevote:
            ttl: 90ms
        acceptVote:
            ttl: 90ms
        delay: 2s
        eventChanSize: 1024
    blockCreationInterval: 1s

blockSync:
    interval: 700ms

delegate:
    addrs:
        - "127.0.0.1:40000"
        - "127.0.0.1:40001"
        - "127.0.0.1:40002"
        - "127.0.0.1:40003"

rpc:
    addr: "127.0.0.1:42124"

dispatcher:
    eventchansize: 1024
