# go-yaml expects the YAML field corresponding to a struct field to be lowercase. So if your struct field is
# UpdateInterval, the corresponding field in YAML is updateinterval.

nodetype: "delegate"            # should be one of "delegate", "full_node", and "lightweight"

network:
    addr: "127.0.0.1:4689"
    msglogscleaninginterval: 2s
    msglogretention: 10s
    healthcheckinterval: 1s
    silentinterval: 5s
    peermaintainerinterval: 1s
    allowmulticonnsperip: true
    numpeerslowerbound: 5
    numpeersupperbound: 5
    pinginterval: 1s
    ratelimitenabled: false
    ratelimitpersec: 5
    ratelimitwindowsize: 60s
    bootstrapnodes:
        - "127.0.0.1:4689"
    maxmsgsize: 10485760
    peerdiscovery: true

chain:
    chaindbpath: "./chain.db"
    triedbpath: "./trie.db"
    rawmineraddr:
        privatekey: "925f0c9e4b6f6d92f2961d01aff6204c44d73c0b9d0da188582932d4fcad0d8ee8c66600"
        publickey: "336eb60a5741f585a8e81de64e071327a3b96c15af4af5723598a07b6121e8e813bbd0056ba71ae29c0d64252e913f60afaeb11059908b81ff27cbfa327fd371d35f5ec0cbc01705"
        rawaddress: "io1qyqsyqcy8uhx9jtdc2xp5wx7nxyq3xf4c3jmxknzkuej8y"
    inmemtest: false

consensus:
    scheme: "STANDALONE"
    blockcreationinterval: 1s

blocksync:
    interval: 1s

delegate:
    addrs:
        - "127.0.0.1:4689"

rpc:
    port: ":42124"

dispatcher:
    eventchansize: 1024
