# go-yaml expects the YAML field corresponding to a struct field to be lowercase. So if your struct field is
# UpdateInterval, the corresponding field in YAML is updateinterval.

nodeType: "delegate"            # should be one of "delegate", "full_node", and "lightweight"

network:
    addr: "127.0.0.1:4689"
    msgLogsCleaningInterval: 2s
    msgLogRetention: 10s
    healthCheckInterval: 1s
    silentInterval: 5s
    peerMaintainerInterval: 1s
    allowMultiConnsperIP: true
    numPeersLowerBound: 5
    numPeersUpperBound: 5
    pingInterval: 1s
    rateLimitEnabled: false
    rateLimitPerSec: 5
    rateLimitWindowSize: 60s
    bootstrapNodes:
        - "127.0.0.1:4689"
    maxMsgSize: 10485760
    peerDiscovery: true
    ttl: 3

chain:
    chainDBPath: "./chain.db"
    trieDBPath: "./trie.db"
    rawMinerAddr:
    producerPrivKey: "925f0c9e4b6f6d92f2961d01aff6204c44d73c0b9d0da188582932d4fcad0d8ee8c66600"
    producerPubKey: "336eb60a5741f585a8e81de64e071327a3b96c15af4af5723598a07b6121e8e813bbd0056ba71ae29c0d64252e913f60afaeb11059908b81ff27cbfa327fd371d35f5ec0cbc01705"
    inMemTest: false

consensus:
    scheme: "STANDALONE"
    blockCreationInterval: 1s

blockSync:
    interval: 1s

delegate:
    addrs:
        - "127.0.0.1:4689"

dispatcher:
    eventChanSize: 1024

explorer:
    enabled: true
    isTest: false
    addr: "14004"
    tpsWindow: 10

actPool:
    maxNumActPerPool: 32768
    maxNumActPerAcct: 2048