# go-yaml expects the YAML field corresponding to a struct field to be lowercase. So if your struct field is
# UpdateInterval, the corresponding field in YAML is updateinterval.

nodeType: "delegate"            # should be one of "delegate", "full_node", and "lightweight"

network:
    ip: "127.0.0.1"
    port: 4689
    bootstrapNodes:
        - "127.0.0.1:4689"
        - "127.0.0.1:10000"

chain:
    chainDBPath: "./chain.db"
    trieDBPath: "./trie.db"
    producerPrivKey: "925f0c9e4b6f6d92f2961d01aff6204c44d73c0b9d0da188582932d4fcad0d8ee8c66600"
    producerPubKey: "336eb60a5741f585a8e81de64e071327a3b96c15af4af5723598a07b6121e8e813bbd0056ba71ae29c0d64252e913f60afaeb11059908b81ff27cbfa327fd371d35f5ec0cbc01705"

consensus:
    scheme: "STANDALONE"
    blockCreationInterval: 1s

blockSync:
    interval: 1s

delegate:
    addrs:
        - "io1qyqsyqcy8uhx9jtdc2xp5wx7nxyq3xf4c3jmxknzkuej8y"

