# go-yaml expects the YAML field corresponding to a struct field to be lowercase. So if your struct field is
# UpdateInterval, the corresponding field in YAML is updateinterval.

network:
    host: "127.0.0.1"
    port: 4689

chain:
    chainDBPath: "./chain.db"
    trieDBPath: "./trie.db"
    enableFallbackToFreshDb: true

consensus:
    scheme: "STANDALONE"

blockSync:
    interval: 1s

system:
    httpProfilingPort: 6060

explorer:
    enabled: true

api:
    enabled: true

