# go-yaml expects the YAML field corresponding to a struct field to be lowercase. So if your struct field is
# UpdateInterval, the corresponding field in YAML is updateinterval.


nodeType: "full_node"            # should be one of "delegate", "full_node", and "lightweight"

network:
    addr: "127.0.0.1:10000"
    msgLogsCleaningInterval: 2s
    msgLogRetention: 10s
    healthCheckInterval: 1s
    silentInterval: 5s
    peerMaintainerInterval: 1s
    allowMultiConnsperIP: true
    numPeersLowerBound: 5
    numPeersUpperBound: 5
    pingInterval: 1s
    rateLimitEnabled: false
    rateLimitPerSec: 5
    rateLimitWindowSize: 60s
    bootstrapNodes:
        - "127.0.0.1:4689"
    maxMsgSize: 10485760
    peerDiscovery: true
    ttl: 3

chain:
    chainDBPath: "./db.test"
    trieDBPath: "./trie.db"
    rawMinerAddr:
    producerPrivKey: "7fbb20b87d34eade61351165aa4c6fa5d87dd349368dd6b9034ea3d3e918c706b9b8d7316705dc4ff62bb323e610f3f5072abedc9834e999d6537f6681284ea2"
    producerPubKey: "b9b8d7316705dc4ff62bb323e610f3f5072abedc9834e999d6537f6681284ea2"
    inMemTest: false

consensus:
    scheme: "NOOP"

blockSync:
    interval: 1s

delegate:
    addrs:
        - "127.0.0.1:4689"

rpc:
    addr: "127.0.0.1:42124"

dispatcher:
    eventChanSize: 1024

actPool:
    maxNumActPerPool: 32768
    maxNumActPerAcct: 2048
