name: "Code Scanning - CodeQL"

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  CodeQL-Build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go

      - run: |
          make build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
