name: "Code Scanning -Gosec"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Run Gosec Security Scanner
        uses: securego/gosec@53aee87f9fa5e513efcaaa99e387f9b5e9fbab47 # v2.9.6
        with:
          args: "-no-fail -fmt sarif -out results.sarif ./..."

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@3b1a19a80ab047f35cbb237b5bd9bdc1e14f166c # v3
        with:
          sarif_file: results.sarif
